version: "2"
volumes:
  db:
services:
  postgres:
    image: "postgres"
    stop_signal: SIGINT                 # Fast Shutdown mode
    command: -p 5432
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prod
    restart: unless-stopped
    volumes: 
      - db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - ./.env.prod
    ports:
        - 5672:5672
        - 15672:15672
    restart: unless-stopped
  app:
    image: pkpdapp
    depends_on:
      - postgres
      - rabbitmq
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:${PORT}"
    volumes:
      - .certs:/etc/ssl/pkpdapp
    restart: unless-stopped
    env_file:
     - ./.env.prod
 
  
