version: "2"
volumes:
  db:
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - ./.env.prod
    ports:
        - 5672:5672
        - 15672:15672
    restart: unless-stopped
  app:
    image: pkpdapp
    depends_on:
      - rabbitmq
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 443:443
      - 80:80
    volumes:
      - ${PWD}/.certs/pkpdapp.key:/etc/ssl/pkpdapp.key
      - ${PWD}/.certs/pkpdapp.crt:/etc/ssl/pkpdapp.crt
    restart: unless-stopped
    env_file:
     - ./.env.prod
 
  
