// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { BiomarkerTypeRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const biomarkerTypes = [] as unknown as BiomarkerTypeRead[];

export const biomarkerTypeHandlers = [
  http.get("/api/biomarker_type/", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const datasetId = url.searchParams.get("dataset_id");
    if (datasetId) {
      const filtered = biomarkerTypes.filter(bt => bt.dataset === parseInt(datasetId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(biomarkerTypes, { status: 200 });
  }),
];
