// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { ProjectRead, CompoundRead, UserRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const project = {
  id: 105,
  user_access: [
    {
      id: 124,
      read_only: false,
      user: 2,
      project: 105
    }
  ],
  datasets: [],
  protocols: [
    5092
  ],
  name: "Storybook Test Project",
  description: "Automatically generated for Storybook mocks",
  created: "2026-03-04T16:00:59.379262Z",
  tags: "",
  species: "R",
  species_weight: 0.25,
  version: 3,
  compound: 130,
  species_weight_unit: 41,
  users: [
    2
  ],
  pk_tags: [],
  pd_tags: []
} as unknown as ProjectRead;

export const compound = {
  id: 130,
  efficacy_experiments: [],
  name: "Test Compound",
  description: "Automatically generated test compound for Storybook",
  molecular_mass: 500.0,
  compound_type: "S",
  fraction_unbound_plasma: 0.02,
  blood_to_plasma_ratio: 1.0,
  intrinsic_clearance: null,
  intrinsic_clearance_assay: "MS",
  fraction_unbound_including_cells: 1.0,
  target_molecular_mass: 25000.0,
  target2_molecular_mass: 25000.0,
  target_concentration: 1.0,
  dissociation_constant: null,
  is_soluble: true,
  use_efficacy: null,
  molecular_mass_unit: 54,
  intrinsic_clearance_unit: 8,
  target_molecular_mass_unit: 54,
  target2_molecular_mass_unit: 54,
  target_concentration_unit: 1,
  dissociation_unit: 1
} as unknown as CompoundRead;

export const users = [
  {
    id: 1,
    username: "jim",
    first_name: "",
    last_name: "",
    email: "james.odonnell@dtc.ox.ac.uk",
    profile: {
      id: 1,
      user: 1
    },
    project_set: [
      1,
      2,
      3,
      7,
      8,
      9,
      11,
      12,
      25,
      26,
      27,
      28,
      29,
      30,
      33,
      36,
      37,
      38,
      39,
      40,
      41,
      43,
      57,
      67,
      68,
      69,
      70,
      71,
      72,
      74,
      103,
      104
    ]
  },
  {
    id: 2,
    username: "storybook_test_user",
    first_name: "Storybook",
    last_name: "Test",
    email: "test@pkpdapp.com",
    profile: {
      id: 2,
      user: 2
    },
    project_set: [
      105
    ]
  }
] as unknown as UserRead[];

export const projectHandlers = [
  http.get("/api/project", async () => {
    await delay();
    return HttpResponse.json([project], { status: 200 });
  }),
  http.get("/api/project/:id", async ({ params }) => {
    await delay();
    //@ts-expect-error params.id is a string
    const projectId = parseInt(params.id, 10);
    if (projectId === project.id) {
      return HttpResponse.json(project, { status: 200 });
    }
    return HttpResponse.json({ error: "Project not found" }, { status: 404 });
  }),
  http.get("/api/user", async () => {
    await delay();
    return HttpResponse.json(users, { status: 200 });
  }),
  http.get("/api/compound/:id", async ({ params }) => {
    await delay();
    //@ts-expect-error params.id is a string
    const compoundId = parseInt(params.id, 10);
    if (compoundId === compound.id) {
      return HttpResponse.json(compound, { status: 200 });
    }
    return HttpResponse.json({ error: "Compound not found" }, { status: 404 });
  }),
];
