// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { SimulationRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const simulations = [] as unknown as SimulationRead[];

export const simulationHandlers = [
  http.get("/api/simulation/", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const projectId = url.searchParams.get("project_id");
    if (projectId) {
      const filtered = simulations.filter(s => s.project === parseInt(projectId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(simulations, { status: 200 });
  }),
];
