// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { SimulationRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const simulations = [
  {
    id: 1,
    sliders: [
      {
        id: 1,
        variable: 4
      },
      {
        id: 2,
        variable: 5
      }
    ],
    plots: [
      {
        id: 1,
        y_axes: [
          {
            id: 1,
            right: false,
            variable: 11
          }
        ],
        cx_lines: [],
        index: 0,
        x_scale: "lin",
        y_scale: "lin",
        y2_scale: "lin",
        x_label: "",
        y_label: "",
        y2_label: "",
        min: null,
        max: null,
        min2: null,
        max2: null,
        x_unit: 20,
        y_unit: 9,
        y_unit2: null
      }
    ],
    name: "default",
    nrows: 1,
    ncols: 1,
    time_max: 30.0,
    abs_tolerance: 1e-06,
    rel_tolerance: 1e-06,
    project: 1,
    time_max_unit: 20
  }
] as unknown as SimulationRead[];

export const simulationHandlers = [
  http.get("/api/simulation/", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const projectId = url.searchParams.get("project_id");
    if (projectId) {
      const filtered = simulations.filter(s => s.project === parseInt(projectId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(simulations, { status: 200 });
  }),
];
