// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { SubjectRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const subjects = [] as unknown as SubjectRead[];

export const subjectHandlers = [
  http.get("/api/subject/", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const datasetId = url.searchParams.get("dataset_id");
    if (datasetId) {
      const filtered = subjects.filter(s => s.dataset === parseInt(datasetId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(subjects, { status: 200 });
  }),
];
