// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { SubjectRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const subjects = [
  {
    id: 667,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 150,
    protocol: 693,
    group: 243
  },
  {
    id: 668,
    id_in_dataset: 2,
    shape: 7,
    display: true,
    metadata: "{}",
    dataset: 150,
    protocol: 693,
    group: 243
  },
  {
    id: 669,
    id_in_dataset: 3,
    shape: 14,
    display: true,
    metadata: "{}",
    dataset: 150,
    protocol: 693,
    group: 243
  },
  {
    id: 670,
    id_in_dataset: 4,
    shape: 21,
    display: true,
    metadata: "{}",
    dataset: 150,
    protocol: 696,
    group: 244
  },
  {
    id: 671,
    id_in_dataset: 5,
    shape: 28,
    display: true,
    metadata: "{}",
    dataset: 150,
    protocol: 696,
    group: 244
  },
  {
    id: 672,
    id_in_dataset: 6,
    shape: 35,
    display: true,
    metadata: "{}",
    dataset: 150,
    protocol: 696,
    group: 244
  },
  {
    id: 673,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 1,
    protocol: 714,
    group: 261
  },
  {
    id: 674,
    id_in_dataset: 2,
    shape: 8,
    display: true,
    metadata: "{}",
    dataset: 1,
    protocol: 714,
    group: 261
  },
  {
    id: 675,
    id_in_dataset: 3,
    shape: 16,
    display: true,
    metadata: "{}",
    dataset: 1,
    protocol: 714,
    group: 261
  },
  {
    id: 676,
    id_in_dataset: 4,
    shape: 24,
    display: true,
    metadata: "{}",
    dataset: 1,
    protocol: 717,
    group: 262
  },
  {
    id: 677,
    id_in_dataset: 5,
    shape: 32,
    display: true,
    metadata: "{}",
    dataset: 1,
    protocol: 717,
    group: 262
  },
  {
    id: 678,
    id_in_dataset: 6,
    shape: 40,
    display: true,
    metadata: "{}",
    dataset: 1,
    protocol: 717,
    group: 262
  },
  {
    id: 679,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 168,
    protocol: 732,
    group: 266
  },
  {
    id: 680,
    id_in_dataset: 2,
    shape: 7,
    display: true,
    metadata: "{}",
    dataset: 168,
    protocol: 732,
    group: 266
  },
  {
    id: 681,
    id_in_dataset: 3,
    shape: 14,
    display: true,
    metadata: "{}",
    dataset: 168,
    protocol: 732,
    group: 266
  },
  {
    id: 682,
    id_in_dataset: 4,
    shape: 21,
    display: true,
    metadata: "{}",
    dataset: 168,
    protocol: 735,
    group: 267
  },
  {
    id: 683,
    id_in_dataset: 5,
    shape: 28,
    display: true,
    metadata: "{}",
    dataset: 168,
    protocol: 735,
    group: 267
  },
  {
    id: 684,
    id_in_dataset: 6,
    shape: 35,
    display: true,
    metadata: "{}",
    dataset: 168,
    protocol: 735,
    group: 267
  },
  {
    id: 691,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 173,
    protocol: 746,
    group: 270
  },
  {
    id: 692,
    id_in_dataset: 2,
    shape: 7,
    display: true,
    metadata: "{}",
    dataset: 173,
    protocol: 746,
    group: 270
  },
  {
    id: 693,
    id_in_dataset: 3,
    shape: 14,
    display: true,
    metadata: "{}",
    dataset: 173,
    protocol: 746,
    group: 270
  },
  {
    id: 694,
    id_in_dataset: 4,
    shape: 21,
    display: true,
    metadata: "{}",
    dataset: 173,
    protocol: 746,
    group: 270
  },
  {
    id: 695,
    id_in_dataset: 5,
    shape: 28,
    display: true,
    metadata: "{}",
    dataset: 173,
    protocol: 746,
    group: 270
  },
  {
    id: 696,
    id_in_dataset: 6,
    shape: 35,
    display: true,
    metadata: "{}",
    dataset: 173,
    protocol: 746,
    group: 270
  },
  {
    id: 714,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 178,
    protocol: 770,
    group: 280
  },
  {
    id: 805,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 188,
    protocol: 877,
    group: 333
  },
  {
    id: 995,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 144,
    protocol: 1090,
    group: 399
  },
  {
    id: 996,
    id_in_dataset: 2,
    shape: 15,
    display: true,
    metadata: "{}",
    dataset: 144,
    protocol: 1090,
    group: 399
  },
  {
    id: 997,
    id_in_dataset: 3,
    shape: 30,
    display: true,
    metadata: "{}",
    dataset: 144,
    protocol: 1090,
    group: 399
  },
  {
    id: 998,
    id_in_dataset: 4,
    shape: 45,
    display: true,
    metadata: "{}",
    dataset: 144,
    protocol: 1093,
    group: 400
  },
  {
    id: 999,
    id_in_dataset: 5,
    shape: 60,
    display: true,
    metadata: "{}",
    dataset: 144,
    protocol: 1093,
    group: 400
  },
  {
    id: 1000,
    id_in_dataset: 6,
    shape: 75,
    display: true,
    metadata: "{}",
    dataset: 144,
    protocol: 1093,
    group: 400
  },
  {
    id: 1007,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 232,
    protocol: 1103,
    group: 403
  },
  {
    id: 1008,
    id_in_dataset: 2,
    shape: 15,
    display: true,
    metadata: "{}",
    dataset: 232,
    protocol: 1103,
    group: 403
  },
  {
    id: 1009,
    id_in_dataset: 3,
    shape: 30,
    display: true,
    metadata: "{}",
    dataset: 232,
    protocol: 1103,
    group: 403
  },
  {
    id: 1010,
    id_in_dataset: 4,
    shape: 45,
    display: true,
    metadata: "{}",
    dataset: 232,
    protocol: 1106,
    group: 404
  },
  {
    id: 1011,
    id_in_dataset: 5,
    shape: 60,
    display: true,
    metadata: "{}",
    dataset: 232,
    protocol: 1106,
    group: 404
  },
  {
    id: 1012,
    id_in_dataset: 6,
    shape: 75,
    display: true,
    metadata: "{}",
    dataset: 232,
    protocol: 1106,
    group: 404
  },
  {
    id: 1043,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 237,
    protocol: 1165,
    group: 421
  },
  {
    id: 1044,
    id_in_dataset: 2,
    shape: 7,
    display: true,
    metadata: "{}",
    dataset: 237,
    protocol: 1165,
    group: 421
  },
  {
    id: 1045,
    id_in_dataset: 3,
    shape: 14,
    display: true,
    metadata: "{}",
    dataset: 237,
    protocol: 1165,
    group: 421
  },
  {
    id: 1046,
    id_in_dataset: 4,
    shape: 21,
    display: true,
    metadata: "{}",
    dataset: 237,
    protocol: 1168,
    group: 422
  },
  {
    id: 1047,
    id_in_dataset: 5,
    shape: 28,
    display: true,
    metadata: "{}",
    dataset: 237,
    protocol: 1168,
    group: 422
  },
  {
    id: 1048,
    id_in_dataset: 6,
    shape: 35,
    display: true,
    metadata: "{}",
    dataset: 237,
    protocol: 1168,
    group: 422
  },
  {
    id: 1121,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 197,
    protocol: 1248,
    group: 448
  },
  {
    id: 1122,
    id_in_dataset: 2,
    shape: 15,
    display: true,
    metadata: "{}",
    dataset: 197,
    protocol: 1248,
    group: 448
  },
  {
    id: 1123,
    id_in_dataset: 3,
    shape: 30,
    display: true,
    metadata: "{}",
    dataset: 197,
    protocol: 1248,
    group: 448
  },
  {
    id: 1124,
    id_in_dataset: 4,
    shape: 45,
    display: true,
    metadata: "{}",
    dataset: 197,
    protocol: 1251,
    group: 449
  },
  {
    id: 1125,
    id_in_dataset: 5,
    shape: 60,
    display: true,
    metadata: "{}",
    dataset: 197,
    protocol: 1251,
    group: 449
  },
  {
    id: 1126,
    id_in_dataset: 6,
    shape: 75,
    display: true,
    metadata: "{}",
    dataset: 197,
    protocol: 1251,
    group: 449
  },
  {
    id: 1529,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 233,
    protocol: 1679,
    group: 593
  },
  {
    id: 1530,
    id_in_dataset: 2,
    shape: 15,
    display: true,
    metadata: "{}",
    dataset: 233,
    protocol: 1679,
    group: 593
  },
  {
    id: 1531,
    id_in_dataset: 3,
    shape: 30,
    display: true,
    metadata: "{}",
    dataset: 233,
    protocol: 1679,
    group: 593
  },
  {
    id: 1532,
    id_in_dataset: 4,
    shape: 45,
    display: true,
    metadata: "{}",
    dataset: 233,
    protocol: 1682,
    group: 594
  },
  {
    id: 1533,
    id_in_dataset: 5,
    shape: 60,
    display: true,
    metadata: "{}",
    dataset: 233,
    protocol: 1682,
    group: 594
  },
  {
    id: 1534,
    id_in_dataset: 6,
    shape: 75,
    display: true,
    metadata: "{}",
    dataset: 233,
    protocol: 1682,
    group: 594
  },
  {
    id: 1632,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 236,
    protocol: 1813,
    group: 653
  },
  {
    id: 1633,
    id_in_dataset: 2,
    shape: 8,
    display: true,
    metadata: "{}",
    dataset: 236,
    protocol: 1813,
    group: 653
  },
  {
    id: 1634,
    id_in_dataset: 3,
    shape: 16,
    display: true,
    metadata: "{}",
    dataset: 236,
    protocol: 1813,
    group: 653
  },
  {
    id: 1635,
    id_in_dataset: 4,
    shape: 24,
    display: true,
    metadata: "{}",
    dataset: 236,
    protocol: 1816,
    group: 654
  },
  {
    id: 1636,
    id_in_dataset: 5,
    shape: 32,
    display: true,
    metadata: "{}",
    dataset: 236,
    protocol: 1816,
    group: 654
  },
  {
    id: 1637,
    id_in_dataset: 6,
    shape: 40,
    display: true,
    metadata: "{}",
    dataset: 236,
    protocol: 1816,
    group: 654
  },
  {
    id: 3466,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 244,
    protocol: null,
    group: 1344
  },
  {
    id: 3467,
    id_in_dataset: 2,
    shape: 15,
    display: true,
    metadata: "{}",
    dataset: 244,
    protocol: null,
    group: 1344
  },
  {
    id: 3468,
    id_in_dataset: 3,
    shape: 30,
    display: true,
    metadata: "{}",
    dataset: 244,
    protocol: null,
    group: 1344
  },
  {
    id: 3469,
    id_in_dataset: 4,
    shape: 45,
    display: true,
    metadata: "{}",
    dataset: 244,
    protocol: null,
    group: 1345
  },
  {
    id: 3470,
    id_in_dataset: 5,
    shape: 60,
    display: true,
    metadata: "{}",
    dataset: 244,
    protocol: null,
    group: 1345
  },
  {
    id: 3471,
    id_in_dataset: 6,
    shape: 75,
    display: true,
    metadata: "{}",
    dataset: 244,
    protocol: null,
    group: 1345
  },
  {
    id: 4047,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 240,
    protocol: null,
    group: 1520
  },
  {
    id: 4048,
    id_in_dataset: 2,
    shape: 2,
    display: true,
    metadata: "{}",
    dataset: 240,
    protocol: null,
    group: 1521
  },
  {
    id: 4049,
    id_in_dataset: 3,
    shape: 4,
    display: true,
    metadata: "{}",
    dataset: 240,
    protocol: null,
    group: 1522
  },
  {
    id: 4050,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 243,
    protocol: null,
    group: 1523
  },
  {
    id: 4051,
    id_in_dataset: 2,
    shape: 2,
    display: true,
    metadata: "{}",
    dataset: 243,
    protocol: null,
    group: 1524
  },
  {
    id: 4052,
    id_in_dataset: 3,
    shape: 4,
    display: true,
    metadata: "{}",
    dataset: 243,
    protocol: null,
    group: 1525
  },
  {
    id: 4053,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1526
  },
  {
    id: 4054,
    id_in_dataset: 2,
    shape: 12,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1526
  },
  {
    id: 4055,
    id_in_dataset: 3,
    shape: 24,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1526
  },
  {
    id: 4056,
    id_in_dataset: 4,
    shape: 36,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1526
  },
  {
    id: 4057,
    id_in_dataset: 5,
    shape: 48,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1527
  },
  {
    id: 4058,
    id_in_dataset: 6,
    shape: 60,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1527
  },
  {
    id: 4059,
    id_in_dataset: 7,
    shape: 72,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1527
  },
  {
    id: 4060,
    id_in_dataset: 8,
    shape: 84,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1527
  },
  {
    id: 4061,
    id_in_dataset: 9,
    shape: 96,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1528
  },
  {
    id: 4062,
    id_in_dataset: 10,
    shape: 108,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1528
  },
  {
    id: 4063,
    id_in_dataset: 11,
    shape: 120,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1528
  },
  {
    id: 4064,
    id_in_dataset: 12,
    shape: 132,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1528
  },
  {
    id: 4065,
    id_in_dataset: 13,
    shape: 144,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1529
  },
  {
    id: 4066,
    id_in_dataset: 14,
    shape: 156,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1529
  },
  {
    id: 4067,
    id_in_dataset: 15,
    shape: 168,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1529
  },
  {
    id: 4068,
    id_in_dataset: 16,
    shape: 180,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1529
  },
  {
    id: 4069,
    id_in_dataset: 17,
    shape: 192,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1530
  },
  {
    id: 4070,
    id_in_dataset: 18,
    shape: 204,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1530
  },
  {
    id: 4071,
    id_in_dataset: 19,
    shape: 216,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1530
  },
  {
    id: 4072,
    id_in_dataset: 20,
    shape: 228,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1530
  },
  {
    id: 4073,
    id_in_dataset: 21,
    shape: 240,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1531
  },
  {
    id: 4074,
    id_in_dataset: 22,
    shape: 252,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1531
  },
  {
    id: 4075,
    id_in_dataset: 23,
    shape: 264,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1531
  },
  {
    id: 4076,
    id_in_dataset: 24,
    shape: 276,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1531
  },
  {
    id: 4077,
    id_in_dataset: 25,
    shape: 288,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1532
  },
  {
    id: 4078,
    id_in_dataset: 26,
    shape: 300,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1532
  },
  {
    id: 4079,
    id_in_dataset: 27,
    shape: 312,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1532
  },
  {
    id: 4080,
    id_in_dataset: 28,
    shape: 324,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1532
  },
  {
    id: 4081,
    id_in_dataset: 29,
    shape: 336,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1533
  },
  {
    id: 4082,
    id_in_dataset: 30,
    shape: 348,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1533
  },
  {
    id: 4083,
    id_in_dataset: 31,
    shape: 360,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1533
  },
  {
    id: 4084,
    id_in_dataset: 32,
    shape: 372,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1533
  },
  {
    id: 4085,
    id_in_dataset: 33,
    shape: 384,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1534
  },
  {
    id: 4086,
    id_in_dataset: 34,
    shape: 396,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1534
  },
  {
    id: 4087,
    id_in_dataset: 35,
    shape: 408,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1534
  },
  {
    id: 4088,
    id_in_dataset: 36,
    shape: 420,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1534
  },
  {
    id: 4089,
    id_in_dataset: 37,
    shape: 432,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1535
  },
  {
    id: 4090,
    id_in_dataset: 38,
    shape: 444,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1535
  },
  {
    id: 4091,
    id_in_dataset: 39,
    shape: 456,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1535
  },
  {
    id: 4092,
    id_in_dataset: 40,
    shape: 468,
    display: true,
    metadata: "{}",
    dataset: 245,
    protocol: null,
    group: 1535
  },
  {
    id: 4402,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 252,
    protocol: null,
    group: 1634
  },
  {
    id: 4403,
    id_in_dataset: 2,
    shape: 7,
    display: true,
    metadata: "{}",
    dataset: 252,
    protocol: null,
    group: 1634
  },
  {
    id: 4404,
    id_in_dataset: 3,
    shape: 14,
    display: true,
    metadata: "{}",
    dataset: 252,
    protocol: null,
    group: 1634
  },
  {
    id: 4405,
    id_in_dataset: 4,
    shape: 21,
    display: true,
    metadata: "{}",
    dataset: 252,
    protocol: null,
    group: 1635
  },
  {
    id: 4406,
    id_in_dataset: 5,
    shape: 28,
    display: true,
    metadata: "{}",
    dataset: 252,
    protocol: null,
    group: 1635
  },
  {
    id: 4407,
    id_in_dataset: 6,
    shape: 35,
    display: true,
    metadata: "{}",
    dataset: 252,
    protocol: null,
    group: 1635
  },
  {
    id: 4420,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 269,
    protocol: null,
    group: 1648
  },
  {
    id: 4421,
    id_in_dataset: 2,
    shape: 15,
    display: true,
    metadata: "{}",
    dataset: 269,
    protocol: null,
    group: 1648
  },
  {
    id: 4422,
    id_in_dataset: 3,
    shape: 30,
    display: true,
    metadata: "{}",
    dataset: 269,
    protocol: null,
    group: 1648
  },
  {
    id: 4423,
    id_in_dataset: 4,
    shape: 45,
    display: true,
    metadata: "{}",
    dataset: 269,
    protocol: null,
    group: 1649
  },
  {
    id: 4424,
    id_in_dataset: 5,
    shape: 60,
    display: true,
    metadata: "{}",
    dataset: 269,
    protocol: null,
    group: 1649
  },
  {
    id: 4425,
    id_in_dataset: 6,
    shape: 75,
    display: true,
    metadata: "{}",
    dataset: 269,
    protocol: null,
    group: 1649
  },
  {
    id: 4426,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 234,
    protocol: null,
    group: 1685
  },
  {
    id: 4427,
    id_in_dataset: 2,
    shape: 16,
    display: true,
    metadata: "{}",
    dataset: 234,
    protocol: null,
    group: 1685
  },
  {
    id: 4428,
    id_in_dataset: 3,
    shape: 32,
    display: true,
    metadata: "{}",
    dataset: 234,
    protocol: null,
    group: 1685
  },
  {
    id: 4429,
    id_in_dataset: 4,
    shape: 48,
    display: true,
    metadata: "{}",
    dataset: 234,
    protocol: null,
    group: 1686
  },
  {
    id: 4430,
    id_in_dataset: 5,
    shape: 64,
    display: true,
    metadata: "{}",
    dataset: 234,
    protocol: null,
    group: 1686
  },
  {
    id: 4431,
    id_in_dataset: 6,
    shape: 80,
    display: true,
    metadata: "{}",
    dataset: 234,
    protocol: null,
    group: 1686
  },
  {
    id: 4474,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 304,
    protocol: null,
    group: 1702
  },
  {
    id: 4475,
    id_in_dataset: 2,
    shape: 8,
    display: true,
    metadata: "{}",
    dataset: 304,
    protocol: null,
    group: 1702
  },
  {
    id: 4476,
    id_in_dataset: 3,
    shape: 16,
    display: true,
    metadata: "{}",
    dataset: 304,
    protocol: null,
    group: 1702
  },
  {
    id: 4477,
    id_in_dataset: 4,
    shape: 24,
    display: true,
    metadata: "{}",
    dataset: 304,
    protocol: null,
    group: 1703
  },
  {
    id: 4478,
    id_in_dataset: 5,
    shape: 32,
    display: true,
    metadata: "{}",
    dataset: 304,
    protocol: null,
    group: 1703
  },
  {
    id: 4479,
    id_in_dataset: 6,
    shape: 40,
    display: true,
    metadata: "{}",
    dataset: 304,
    protocol: null,
    group: 1703
  },
  {
    id: 4570,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 307,
    protocol: null,
    group: 1734
  },
  {
    id: 4571,
    id_in_dataset: 2,
    shape: 8,
    display: true,
    metadata: "{}",
    dataset: 307,
    protocol: null,
    group: 1734
  },
  {
    id: 4572,
    id_in_dataset: 3,
    shape: 16,
    display: true,
    metadata: "{}",
    dataset: 307,
    protocol: null,
    group: 1734
  },
  {
    id: 4573,
    id_in_dataset: 4,
    shape: 24,
    display: true,
    metadata: "{}",
    dataset: 307,
    protocol: null,
    group: 1735
  },
  {
    id: 4574,
    id_in_dataset: 5,
    shape: 32,
    display: true,
    metadata: "{}",
    dataset: 307,
    protocol: null,
    group: 1735
  },
  {
    id: 4575,
    id_in_dataset: 6,
    shape: 40,
    display: true,
    metadata: "{}",
    dataset: 307,
    protocol: null,
    group: 1735
  },
  {
    id: 4576,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 306,
    protocol: null,
    group: 1739
  },
  {
    id: 4577,
    id_in_dataset: 2,
    shape: 8,
    display: true,
    metadata: "{}",
    dataset: 306,
    protocol: null,
    group: 1739
  },
  {
    id: 4578,
    id_in_dataset: 3,
    shape: 16,
    display: true,
    metadata: "{}",
    dataset: 306,
    protocol: null,
    group: 1739
  },
  {
    id: 4579,
    id_in_dataset: 4,
    shape: 24,
    display: true,
    metadata: "{}",
    dataset: 306,
    protocol: null,
    group: 1740
  },
  {
    id: 4580,
    id_in_dataset: 5,
    shape: 31,
    display: true,
    metadata: "{}",
    dataset: 306,
    protocol: null,
    group: 1740
  },
  {
    id: 4581,
    id_in_dataset: 6,
    shape: 39,
    display: true,
    metadata: "{}",
    dataset: 306,
    protocol: null,
    group: 1740
  },
  {
    id: 6248,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2117
  },
  {
    id: 6249,
    id_in_dataset: 2,
    shape: 10,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2117
  },
  {
    id: 6250,
    id_in_dataset: 3,
    shape: 20,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2117
  },
  {
    id: 6251,
    id_in_dataset: 4,
    shape: 30,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2117
  },
  {
    id: 6252,
    id_in_dataset: 5,
    shape: 39,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2117
  },
  {
    id: 6253,
    id_in_dataset: 6,
    shape: 48,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2118
  },
  {
    id: 6254,
    id_in_dataset: 7,
    shape: 58,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2118
  },
  {
    id: 6255,
    id_in_dataset: 8,
    shape: 68,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2118
  },
  {
    id: 6256,
    id_in_dataset: 9,
    shape: 78,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2118
  },
  {
    id: 6257,
    id_in_dataset: 10,
    shape: 88,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2118
  },
  {
    id: 6258,
    id_in_dataset: 11,
    shape: 98,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2119
  },
  {
    id: 6259,
    id_in_dataset: 12,
    shape: 108,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2119
  },
  {
    id: 6260,
    id_in_dataset: 13,
    shape: 118,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2119
  },
  {
    id: 6261,
    id_in_dataset: 14,
    shape: 128,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2119
  },
  {
    id: 6262,
    id_in_dataset: 15,
    shape: 138,
    display: true,
    metadata: "{}",
    dataset: 308,
    protocol: null,
    group: 2119
  },
  {
    id: 6359,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2148
  },
  {
    id: 6360,
    id_in_dataset: 2,
    shape: 10,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2148
  },
  {
    id: 6361,
    id_in_dataset: 3,
    shape: 20,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2148
  },
  {
    id: 6362,
    id_in_dataset: 4,
    shape: 30,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2148
  },
  {
    id: 6363,
    id_in_dataset: 5,
    shape: 39,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2148
  },
  {
    id: 6364,
    id_in_dataset: 6,
    shape: 48,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2149
  },
  {
    id: 6365,
    id_in_dataset: 7,
    shape: 58,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2149
  },
  {
    id: 6366,
    id_in_dataset: 8,
    shape: 68,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2149
  },
  {
    id: 6367,
    id_in_dataset: 9,
    shape: 78,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2149
  },
  {
    id: 6368,
    id_in_dataset: 10,
    shape: 88,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2149
  },
  {
    id: 6369,
    id_in_dataset: 11,
    shape: 98,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2150
  },
  {
    id: 6370,
    id_in_dataset: 12,
    shape: 108,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2150
  },
  {
    id: 6371,
    id_in_dataset: 13,
    shape: 118,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2150
  },
  {
    id: 6372,
    id_in_dataset: 14,
    shape: 128,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2150
  },
  {
    id: 6373,
    id_in_dataset: 15,
    shape: 138,
    display: true,
    metadata: "{}",
    dataset: 337,
    protocol: null,
    group: 2150
  },
  {
    id: 6770,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2231
  },
  {
    id: 6771,
    id_in_dataset: 2,
    shape: 12,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2231
  },
  {
    id: 6772,
    id_in_dataset: 3,
    shape: 24,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2231
  },
  {
    id: 6773,
    id_in_dataset: 4,
    shape: 36,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2231
  },
  {
    id: 6774,
    id_in_dataset: 5,
    shape: 47,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2231
  },
  {
    id: 6775,
    id_in_dataset: 6,
    shape: 58,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2232
  },
  {
    id: 6776,
    id_in_dataset: 7,
    shape: 70,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2232
  },
  {
    id: 6777,
    id_in_dataset: 8,
    shape: 82,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2232
  },
  {
    id: 6778,
    id_in_dataset: 9,
    shape: 94,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2232
  },
  {
    id: 6779,
    id_in_dataset: 10,
    shape: 106,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2232
  },
  {
    id: 6780,
    id_in_dataset: 11,
    shape: 118,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2233
  },
  {
    id: 6781,
    id_in_dataset: 12,
    shape: 130,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2233
  },
  {
    id: 6782,
    id_in_dataset: 13,
    shape: 142,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2233
  },
  {
    id: 6783,
    id_in_dataset: 14,
    shape: 154,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2233
  },
  {
    id: 6784,
    id_in_dataset: 15,
    shape: 166,
    display: true,
    metadata: "{}",
    dataset: 338,
    protocol: null,
    group: 2233
  }
] as unknown as SubjectRead[];

export const subjectHandlers = [
  http.get("/api/subject/", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const datasetId = url.searchParams.get("dataset_id");
    if (datasetId) {
      const filtered = subjects.filter(s => s.dataset === parseInt(datasetId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(subjects, { status: 200 });
  }),
];
