// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { SubjectRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const subjects = [
  {
    id: 1,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 1,
    protocol: null,
    group: 1
  },
  {
    id: 2,
    id_in_dataset: 2,
    shape: 8,
    display: true,
    metadata: "{}",
    dataset: 1,
    protocol: null,
    group: 1
  },
  {
    id: 3,
    id_in_dataset: 3,
    shape: 16,
    display: true,
    metadata: "{}",
    dataset: 1,
    protocol: null,
    group: 1
  },
  {
    id: 4,
    id_in_dataset: 4,
    shape: 24,
    display: true,
    metadata: "{}",
    dataset: 1,
    protocol: null,
    group: 2
  },
  {
    id: 5,
    id_in_dataset: 5,
    shape: 32,
    display: true,
    metadata: "{}",
    dataset: 1,
    protocol: null,
    group: 2
  },
  {
    id: 6,
    id_in_dataset: 6,
    shape: 40,
    display: true,
    metadata: "{}",
    dataset: 1,
    protocol: null,
    group: 2
  },
  {
    id: 7,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 2,
    protocol: null,
    group: 3
  },
  {
    id: 8,
    id_in_dataset: 2,
    shape: 9,
    display: true,
    metadata: "{}",
    dataset: 2,
    protocol: null,
    group: 3
  },
  {
    id: 9,
    id_in_dataset: 3,
    shape: 18,
    display: true,
    metadata: "{}",
    dataset: 2,
    protocol: null,
    group: 3
  },
  {
    id: 10,
    id_in_dataset: 4,
    shape: 27,
    display: true,
    metadata: "{}",
    dataset: 2,
    protocol: null,
    group: 4
  },
  {
    id: 11,
    id_in_dataset: 5,
    shape: 37,
    display: true,
    metadata: "{}",
    dataset: 2,
    protocol: null,
    group: 4
  },
  {
    id: 12,
    id_in_dataset: 6,
    shape: 47,
    display: true,
    metadata: "{}",
    dataset: 2,
    protocol: null,
    group: 4
  },
  {
    id: 13,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 3,
    protocol: null,
    group: 5
  },
  {
    id: 14,
    id_in_dataset: 2,
    shape: 9,
    display: true,
    metadata: "{}",
    dataset: 3,
    protocol: null,
    group: 5
  },
  {
    id: 15,
    id_in_dataset: 3,
    shape: 18,
    display: true,
    metadata: "{}",
    dataset: 3,
    protocol: null,
    group: 5
  },
  {
    id: 16,
    id_in_dataset: 4,
    shape: 27,
    display: true,
    metadata: "{}",
    dataset: 3,
    protocol: null,
    group: 6
  },
  {
    id: 17,
    id_in_dataset: 5,
    shape: 37,
    display: true,
    metadata: "{}",
    dataset: 3,
    protocol: null,
    group: 6
  },
  {
    id: 18,
    id_in_dataset: 6,
    shape: 47,
    display: true,
    metadata: "{}",
    dataset: 3,
    protocol: null,
    group: 6
  },
  {
    id: 19,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 4,
    protocol: null,
    group: 7
  },
  {
    id: 20,
    id_in_dataset: 2,
    shape: 9,
    display: true,
    metadata: "{}",
    dataset: 4,
    protocol: null,
    group: 7
  },
  {
    id: 21,
    id_in_dataset: 3,
    shape: 18,
    display: true,
    metadata: "{}",
    dataset: 4,
    protocol: null,
    group: 7
  },
  {
    id: 22,
    id_in_dataset: 4,
    shape: 27,
    display: true,
    metadata: "{}",
    dataset: 4,
    protocol: null,
    group: 8
  },
  {
    id: 23,
    id_in_dataset: 5,
    shape: 37,
    display: true,
    metadata: "{}",
    dataset: 4,
    protocol: null,
    group: 8
  },
  {
    id: 24,
    id_in_dataset: 6,
    shape: 47,
    display: true,
    metadata: "{}",
    dataset: 4,
    protocol: null,
    group: 8
  },
  {
    id: 25,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 5,
    protocol: null,
    group: 9
  },
  {
    id: 26,
    id_in_dataset: 2,
    shape: 9,
    display: true,
    metadata: "{}",
    dataset: 5,
    protocol: null,
    group: 9
  },
  {
    id: 27,
    id_in_dataset: 3,
    shape: 18,
    display: true,
    metadata: "{}",
    dataset: 5,
    protocol: null,
    group: 9
  },
  {
    id: 28,
    id_in_dataset: 4,
    shape: 27,
    display: true,
    metadata: "{}",
    dataset: 5,
    protocol: null,
    group: 10
  },
  {
    id: 29,
    id_in_dataset: 5,
    shape: 37,
    display: true,
    metadata: "{}",
    dataset: 5,
    protocol: null,
    group: 10
  },
  {
    id: 30,
    id_in_dataset: 6,
    shape: 47,
    display: true,
    metadata: "{}",
    dataset: 5,
    protocol: null,
    group: 10
  },
  {
    id: 31,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 6,
    protocol: null,
    group: 11
  },
  {
    id: 32,
    id_in_dataset: 2,
    shape: 9,
    display: true,
    metadata: "{}",
    dataset: 6,
    protocol: null,
    group: 11
  },
  {
    id: 33,
    id_in_dataset: 3,
    shape: 18,
    display: true,
    metadata: "{}",
    dataset: 6,
    protocol: null,
    group: 11
  },
  {
    id: 34,
    id_in_dataset: 4,
    shape: 27,
    display: true,
    metadata: "{}",
    dataset: 6,
    protocol: null,
    group: 12
  },
  {
    id: 35,
    id_in_dataset: 5,
    shape: 37,
    display: true,
    metadata: "{}",
    dataset: 6,
    protocol: null,
    group: 12
  },
  {
    id: 36,
    id_in_dataset: 6,
    shape: 47,
    display: true,
    metadata: "{}",
    dataset: 6,
    protocol: null,
    group: 12
  },
  {
    id: 37,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 7,
    protocol: null,
    group: 13
  },
  {
    id: 38,
    id_in_dataset: 2,
    shape: 9,
    display: true,
    metadata: "{}",
    dataset: 7,
    protocol: null,
    group: 13
  },
  {
    id: 39,
    id_in_dataset: 3,
    shape: 18,
    display: true,
    metadata: "{}",
    dataset: 7,
    protocol: null,
    group: 13
  },
  {
    id: 40,
    id_in_dataset: 4,
    shape: 27,
    display: true,
    metadata: "{}",
    dataset: 7,
    protocol: null,
    group: 14
  },
  {
    id: 41,
    id_in_dataset: 5,
    shape: 37,
    display: true,
    metadata: "{}",
    dataset: 7,
    protocol: null,
    group: 14
  },
  {
    id: 42,
    id_in_dataset: 6,
    shape: 47,
    display: true,
    metadata: "{}",
    dataset: 7,
    protocol: null,
    group: 14
  },
  {
    id: 43,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 8,
    protocol: null,
    group: 15
  },
  {
    id: 44,
    id_in_dataset: 2,
    shape: 9,
    display: true,
    metadata: "{}",
    dataset: 8,
    protocol: null,
    group: 15
  },
  {
    id: 45,
    id_in_dataset: 3,
    shape: 18,
    display: true,
    metadata: "{}",
    dataset: 8,
    protocol: null,
    group: 15
  },
  {
    id: 46,
    id_in_dataset: 4,
    shape: 27,
    display: true,
    metadata: "{}",
    dataset: 8,
    protocol: null,
    group: 16
  },
  {
    id: 47,
    id_in_dataset: 5,
    shape: 37,
    display: true,
    metadata: "{}",
    dataset: 8,
    protocol: null,
    group: 16
  },
  {
    id: 48,
    id_in_dataset: 6,
    shape: 47,
    display: true,
    metadata: "{}",
    dataset: 8,
    protocol: null,
    group: 16
  },
  {
    id: 49,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 9,
    protocol: null,
    group: 17
  },
  {
    id: 50,
    id_in_dataset: 2,
    shape: 9,
    display: true,
    metadata: "{}",
    dataset: 9,
    protocol: null,
    group: 17
  },
  {
    id: 51,
    id_in_dataset: 3,
    shape: 18,
    display: true,
    metadata: "{}",
    dataset: 9,
    protocol: null,
    group: 17
  },
  {
    id: 52,
    id_in_dataset: 4,
    shape: 27,
    display: true,
    metadata: "{}",
    dataset: 9,
    protocol: null,
    group: 18
  },
  {
    id: 53,
    id_in_dataset: 5,
    shape: 37,
    display: true,
    metadata: "{}",
    dataset: 9,
    protocol: null,
    group: 18
  },
  {
    id: 54,
    id_in_dataset: 6,
    shape: 47,
    display: true,
    metadata: "{}",
    dataset: 9,
    protocol: null,
    group: 18
  },
  {
    id: 55,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 10,
    protocol: null,
    group: 19
  },
  {
    id: 56,
    id_in_dataset: 2,
    shape: 9,
    display: true,
    metadata: "{}",
    dataset: 10,
    protocol: null,
    group: 19
  },
  {
    id: 57,
    id_in_dataset: 3,
    shape: 18,
    display: true,
    metadata: "{}",
    dataset: 10,
    protocol: null,
    group: 19
  },
  {
    id: 58,
    id_in_dataset: 4,
    shape: 27,
    display: true,
    metadata: "{}",
    dataset: 10,
    protocol: null,
    group: 20
  },
  {
    id: 59,
    id_in_dataset: 5,
    shape: 37,
    display: true,
    metadata: "{}",
    dataset: 10,
    protocol: null,
    group: 20
  },
  {
    id: 60,
    id_in_dataset: 6,
    shape: 47,
    display: true,
    metadata: "{}",
    dataset: 10,
    protocol: null,
    group: 20
  },
  {
    id: 61,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 11,
    protocol: null,
    group: 21
  },
  {
    id: 62,
    id_in_dataset: 2,
    shape: 9,
    display: true,
    metadata: "{}",
    dataset: 11,
    protocol: null,
    group: 21
  },
  {
    id: 63,
    id_in_dataset: 3,
    shape: 18,
    display: true,
    metadata: "{}",
    dataset: 11,
    protocol: null,
    group: 21
  },
  {
    id: 64,
    id_in_dataset: 4,
    shape: 27,
    display: true,
    metadata: "{}",
    dataset: 11,
    protocol: null,
    group: 22
  },
  {
    id: 65,
    id_in_dataset: 5,
    shape: 37,
    display: true,
    metadata: "{}",
    dataset: 11,
    protocol: null,
    group: 22
  },
  {
    id: 66,
    id_in_dataset: 6,
    shape: 47,
    display: true,
    metadata: "{}",
    dataset: 11,
    protocol: null,
    group: 22
  }
] as unknown as SubjectRead[];

export const subjectHandlers = [
  http.get("/api/subject/", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const datasetId = url.searchParams.get("dataset_id");
    if (datasetId) {
      const filtered = subjects.filter(s => s.dataset === parseInt(datasetId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(subjects, { status: 200 });
  }),
];
