// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { SubjectGroupRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const subjectGroups = [
  {
    id: 1,
    subjects: [
      1,
      2,
      3
    ],
    protocols: [
      {
        id: 20,
        doses: [
          {
            id: 22,
            start_time: 0.0,
            amount: 0.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 20
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "New Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 1,
        project: 19,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 238,
        group: 1
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 1,
    project: 19
  },
  {
    id: 2,
    subjects: [
      4,
      5,
      6
    ],
    protocols: [
      {
        id: 21,
        doses: [
          {
            id: 20,
            start_time: 0.0,
            amount: 500.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 21
          },
          {
            id: 21,
            start_time: 0.0,
            amount: 100.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 21
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "New Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 1,
        project: 19,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 238,
        group: 2
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 1,
    project: 19
  },
  {
    id: 3,
    subjects: [
      7,
      8,
      9
    ],
    protocols: [
      {
        id: 23,
        doses: [
          {
            id: 26,
            start_time: 0.0,
            amount: 0.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 23
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 2,
        project: 20,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 255,
        group: 3
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 2,
    project: 20
  },
  {
    id: 4,
    subjects: [
      10,
      11,
      12
    ],
    protocols: [
      {
        id: 24,
        doses: [
          {
            id: 24,
            start_time: 0.0,
            amount: 500.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 24
          },
          {
            id: 25,
            start_time: 0.0,
            amount: 100.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 24
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 2,
        project: 20,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 255,
        group: 4
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 2,
    project: 20
  },
  {
    id: 5,
    subjects: [
      13,
      14,
      15
    ],
    protocols: [
      {
        id: 26,
        doses: [
          {
            id: 30,
            start_time: 0.0,
            amount: 0.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 26
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 3,
        project: 21,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 268,
        group: 5
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 3,
    project: 21
  },
  {
    id: 6,
    subjects: [
      16,
      17,
      18
    ],
    protocols: [
      {
        id: 27,
        doses: [
          {
            id: 28,
            start_time: 0.0,
            amount: 500.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 27
          },
          {
            id: 29,
            start_time: 0.0,
            amount: 100.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 27
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 3,
        project: 21,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 268,
        group: 6
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 3,
    project: 21
  },
  {
    id: 7,
    subjects: [
      19,
      20,
      21
    ],
    protocols: [
      {
        id: 29,
        doses: [
          {
            id: 34,
            start_time: 0.0,
            amount: 0.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 29
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 4,
        project: 22,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 281,
        group: 7
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 4,
    project: 22
  },
  {
    id: 8,
    subjects: [
      22,
      23,
      24
    ],
    protocols: [
      {
        id: 30,
        doses: [
          {
            id: 32,
            start_time: 0.0,
            amount: 500.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 30
          },
          {
            id: 33,
            start_time: 0.0,
            amount: 100.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 30
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 4,
        project: 22,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 281,
        group: 8
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 4,
    project: 22
  },
  {
    id: 9,
    subjects: [
      25,
      26,
      27
    ],
    protocols: [
      {
        id: 32,
        doses: [
          {
            id: 38,
            start_time: 0.0,
            amount: 0.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 32
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 5,
        project: 23,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 294,
        group: 9
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 5,
    project: 23
  },
  {
    id: 10,
    subjects: [
      28,
      29,
      30
    ],
    protocols: [
      {
        id: 33,
        doses: [
          {
            id: 36,
            start_time: 0.0,
            amount: 500.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 33
          },
          {
            id: 37,
            start_time: 0.0,
            amount: 100.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 33
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 5,
        project: 23,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 294,
        group: 10
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 5,
    project: 23
  },
  {
    id: 11,
    subjects: [
      31,
      32,
      33
    ],
    protocols: [
      {
        id: 35,
        doses: [
          {
            id: 42,
            start_time: 0.0,
            amount: 0.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 35
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 6,
        project: 24,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 307,
        group: 11
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 6,
    project: 24
  },
  {
    id: 12,
    subjects: [
      34,
      35,
      36
    ],
    protocols: [
      {
        id: 36,
        doses: [
          {
            id: 40,
            start_time: 0.0,
            amount: 500.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 36
          },
          {
            id: 41,
            start_time: 0.0,
            amount: 100.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 36
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 6,
        project: 24,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 307,
        group: 12
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 6,
    project: 24
  },
  {
    id: 13,
    subjects: [
      37,
      38,
      39
    ],
    protocols: [
      {
        id: 38,
        doses: [
          {
            id: 46,
            start_time: 0.0,
            amount: 0.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 38
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 7,
        project: 25,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 320,
        group: 13
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 7,
    project: 25
  },
  {
    id: 14,
    subjects: [
      40,
      41,
      42
    ],
    protocols: [
      {
        id: 39,
        doses: [
          {
            id: 44,
            start_time: 0.0,
            amount: 500.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 39
          },
          {
            id: 45,
            start_time: 0.0,
            amount: 100.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 39
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 7,
        project: 25,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 320,
        group: 14
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 7,
    project: 25
  },
  {
    id: 15,
    subjects: [
      43,
      44,
      45
    ],
    protocols: [
      {
        id: 41,
        doses: [
          {
            id: 50,
            start_time: 0.0,
            amount: 0.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 41
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 8,
        project: 26,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 333,
        group: 15
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 8,
    project: 26
  },
  {
    id: 16,
    subjects: [
      46,
      47,
      48
    ],
    protocols: [
      {
        id: 42,
        doses: [
          {
            id: 48,
            start_time: 0.0,
            amount: 500.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 42
          },
          {
            id: 49,
            start_time: 0.0,
            amount: 100.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 42
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 8,
        project: 26,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 333,
        group: 16
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 8,
    project: 26
  },
  {
    id: 17,
    subjects: [
      49,
      50,
      51
    ],
    protocols: [
      {
        id: 44,
        doses: [
          {
            id: 54,
            start_time: 0.0,
            amount: 0.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 44
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 9,
        project: 27,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 346,
        group: 17
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 9,
    project: 27
  },
  {
    id: 18,
    subjects: [
      52,
      53,
      54
    ],
    protocols: [
      {
        id: 45,
        doses: [
          {
            id: 52,
            start_time: 0.0,
            amount: 500.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 45
          },
          {
            id: 53,
            start_time: 0.0,
            amount: 100.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 45
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: false,
        dataset: 9,
        project: 27,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 346,
        group: 18
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 9,
    project: 27
  },
  {
    id: 19,
    subjects: [
      55,
      56,
      57
    ],
    protocols: [
      {
        id: 47,
        doses: [
          {
            id: 58,
            start_time: 0.0,
            amount: 0.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 47
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: true,
        dataset: 10,
        project: 28,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 359,
        group: 19
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 10,
    project: 28
  },
  {
    id: 20,
    subjects: [
      58,
      59,
      60
    ],
    protocols: [
      {
        id: 48,
        doses: [
          {
            id: 56,
            start_time: 0.0,
            amount: 500.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 48
          },
          {
            id: 57,
            start_time: 0.0,
            amount: 100.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 48
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: true,
        dataset: 10,
        project: 28,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 359,
        group: 20
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 10,
    project: 28
  }
] as unknown as SubjectGroupRead[];

export const subjectGroupHandlers = [
  http.get("/api/subject_group/", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const projectId = url.searchParams.get("project_id");
    if (projectId) {
      const filtered = subjectGroups.filter(sg => sg.project === parseInt(projectId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(subjectGroups, { status: 200 });
  }),
];
