// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { SubjectGroupRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const subjectGroups = [] as unknown as SubjectGroupRead[];

export const subjectGroupHandlers = [
  http.get("/api/subject_group/", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const projectId = url.searchParams.get("project_id");
    if (projectId) {
      const filtered = subjectGroups.filter(sg => sg.project === parseInt(projectId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(subjectGroups, { status: 200 });
  }),
];
