// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { ProjectRead, CompoundRead, UserRead } from "../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const project: ProjectRead = {
  id: 3,
  user_access: [
    {
      id: 3,
      read_only: false,
      user: 2,
      project: 3
    }
  ],
  datasets: [],
  protocols: [
    3
  ],
  name: "Storybook Test Project",
  description: "Automatically generated for Storybook mocks",
  created: "2026-02-28T18:36:17.454981Z",
  tags: "",
  species: "R",
  species_weight: 0.25,
  version: 3,
  compound: 3,
  species_weight_unit: 53,
  users: [
    2
  ],
  pk_tags: [],
  pd_tags: []
};

export const compound: CompoundRead = {
  id: 3,
  efficacy_experiments: [],
  name: "Test Compound",
  description: "Automatically generated test compound for Storybook",
  molecular_mass: 500.0,
  compound_type: "S",
  fraction_unbound_plasma: 0.02,
  blood_to_plasma_ratio: 1.0,
  intrinsic_clearance: null,
  intrinsic_clearance_assay: "MS",
  fraction_unbound_including_cells: 1.0,
  target_molecular_mass: 25000.0,
  target2_molecular_mass: 25000.0,
  target_concentration: 1.0,
  dissociation_constant: null,
  is_soluble: true,
  use_efficacy: null,
  molecular_mass_unit: 75,
  intrinsic_clearance_unit: 19,
  target_molecular_mass_unit: 75,
  target2_molecular_mass_unit: 75,
  target_concentration_unit: 10,
  dissociation_unit: 10
};

export const users: UserRead[] = [
  {
    id: 2,
    username: "storybook_test_user",
    first_name: "Storybook",
    last_name: "Test",
    email: "test@pkpdapp.com",
    profile: {
      id: 2,
      user: 2
    },
    project_set: [
      3
    ]
  }
];

export const projectHandlers = [
  http.get("/api/project", async () => {
    await delay();
    return HttpResponse.json([project], { status: 200 });
  }),
  http.get("/api/project/:id", async ({ params }) => {
    await delay();
    //@ts-expect-error params.id is a string
    const projectId = parseInt(params.id, 10);
    if (projectId === project.id) {
      return HttpResponse.json(project, { status: 200 });
    }
    return HttpResponse.json({ error: "Project not found" }, { status: 404 });
  }),
  http.get("/api/user", async () => {
    await delay();
    return HttpResponse.json(users, { status: 200 });
  }),
  http.get("/api/compound/:id", async ({ params }) => {
    await delay();
    //@ts-expect-error params.id is a string
    const compoundId = parseInt(params.id, 10);
    if (compoundId === compound.id) {
      return HttpResponse.json(compound, { status: 200 });
    }
    return HttpResponse.json({ error: "Compound not found" }, { status: 404 });
  }),
];
