// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { ProtocolRead, DoseRead } from "../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const protocols: ProtocolRead[] = [
  {
    id: 3,
    doses: [
      {
        id: 3,
        start_time: 0.0,
        amount: 100.0,
        duration: 0.001,
        repeats: 1,
        repeat_interval: 24.0,
        read_only: false,
        datetime: null,
        protocol: 3
      }
    ],
    subjects: [],
    read_only: false,
    datetime: null,
    name: "Single IV dose",
    dose_type: "D",
    amount_per_body_weight: false,
    dataset: null,
    project: 3,
    compound: 3,
    time_unit: 20,
    amount_unit: 22,
    variable: 33,
    group: null
  }
];

export const dose: DoseRead = {
  id: 3,
  start_time: 0.0,
  amount: 100.0,
  duration: 0.001,
  repeats: 1,
  repeat_interval: 24.0,
  read_only: false,
  datetime: null,
  protocol: 3
};

export const protocolHandlers = [
  http.get("/api/protocol", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const projectId = url.searchParams.get("project_id");
    if (projectId) {
      const filtered = protocols.filter(p => p.project === parseInt(projectId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(protocols, { status: 200 });
  }),
  http.get("/api/dose/:id", async ({ params }) => {
    await delay();
    //@ts-expect-error params.id is a string
    const doseId = parseInt(params.id, 10);
    if (doseId === dose.id) {
      return HttpResponse.json(dose, { status: 200 });
    }
    return HttpResponse.json({ error: "Dose not found" }, { status: 404 });
  }),
];
