// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { ProjectRead, CompoundRead, UserRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const project = {
  id: 33,
  user_access: [
    {
      id: 33,
      read_only: false,
      user: 9,
      project: 33
    }
  ],
  datasets: [
    15
  ],
  protocols: [
    61,
    62,
    63
  ],
  name: "Storybook Test Project",
  description: "Automatically generated for Storybook mocks",
  created: "2026-03-02T08:31:17.576142Z",
  tags: "",
  species: "R",
  species_weight: 0.25,
  version: 3,
  compound: 33,
  species_weight_unit: 53,
  users: [
    9
  ],
  pk_tags: [],
  pd_tags: []
} as unknown as ProjectRead;

export const compound = {
  id: 33,
  efficacy_experiments: [],
  name: "Test Compound",
  description: "Automatically generated test compound for Storybook",
  molecular_mass: 500.0,
  compound_type: "S",
  fraction_unbound_plasma: 0.02,
  blood_to_plasma_ratio: 1.0,
  intrinsic_clearance: null,
  intrinsic_clearance_assay: "MS",
  fraction_unbound_including_cells: 1.0,
  target_molecular_mass: 25000.0,
  target2_molecular_mass: 25000.0,
  target_concentration: 1.0,
  dissociation_constant: null,
  is_soluble: true,
  use_efficacy: null,
  molecular_mass_unit: 75,
  intrinsic_clearance_unit: 19,
  target_molecular_mass_unit: 75,
  target2_molecular_mass_unit: 75,
  target_concentration_unit: 10,
  dissociation_unit: 10
} as unknown as CompoundRead;

export const users = [
  {
    id: 9,
    username: "storybook_test_user",
    first_name: "Storybook",
    last_name: "Test",
    email: "test@pkpdapp.com",
    profile: {
      id: 9,
      user: 9
    },
    project_set: [
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33
    ]
  },
  {
    id: 10,
    username: "test",
    first_name: "",
    last_name: "",
    email: "test@example.com",
    profile: {
      id: 10,
      user: 10
    },
    project_set: [
      19
    ]
  }
] as unknown as UserRead[];

export const projectHandlers = [
  http.get("/api/project", async () => {
    await delay();
    return HttpResponse.json([project], { status: 200 });
  }),
  http.get("/api/project/:id", async ({ params }) => {
    await delay();
    //@ts-expect-error params.id is a string
    const projectId = parseInt(params.id, 10);
    if (projectId === project.id) {
      return HttpResponse.json(project, { status: 200 });
    }
    return HttpResponse.json({ error: "Project not found" }, { status: 404 });
  }),
  http.get("/api/user", async () => {
    await delay();
    return HttpResponse.json(users, { status: 200 });
  }),
  http.get("/api/compound/:id", async ({ params }) => {
    await delay();
    //@ts-expect-error params.id is a string
    const compoundId = parseInt(params.id, 10);
    if (compoundId === compound.id) {
      return HttpResponse.json(compound, { status: 200 });
    }
    return HttpResponse.json({ error: "Compound not found" }, { status: 404 });
  }),
];
