// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { ProtocolRead, DoseRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const protocols = [
  {
    id: 1,
    doses: [
      {
        id: 1,
        start_time: 0.0,
        amount: 100.0,
        duration: 0.001,
        repeats: 1,
        repeat_interval: 24.0,
        read_only: false,
        datetime: null,
        protocol: 1
      }
    ],
    subjects: [],
    read_only: false,
    datetime: null,
    name: "Single IV dose",
    dose_type: "D",
    amount_per_body_weight: false,
    dataset: null,
    project: 1,
    compound: 1,
    time_unit: 20,
    amount_unit: 22,
    variable: 9,
    group: null
  },
  {
    id: 2,
    doses: [
      {
        id: 2,
        start_time: 0.0,
        amount: 10.0,
        duration: 0.0833,
        repeats: 1,
        repeat_interval: 1.0,
        read_only: false,
        datetime: null,
        protocol: 2
      }
    ],
    subjects: [],
    read_only: false,
    datetime: null,
    name: "WithData Test Dataset-Data-Group 1",
    dose_type: "D",
    amount_per_body_weight: true,
    dataset: 1,
    project: 1,
    compound: null,
    time_unit: 20,
    amount_unit: 22,
    variable: 9,
    group: 1
  },
  {
    id: 3,
    doses: [
      {
        id: 3,
        start_time: 0.0,
        amount: 10.0,
        duration: 0.0833,
        repeats: 1,
        repeat_interval: 1.0,
        read_only: false,
        datetime: null,
        protocol: 3
      }
    ],
    subjects: [],
    read_only: false,
    datetime: null,
    name: "WithData Test Dataset-Data-Group 2",
    dose_type: "D",
    amount_per_body_weight: true,
    dataset: 1,
    project: 1,
    compound: null,
    time_unit: 20,
    amount_unit: 22,
    variable: 9,
    group: 2
  }
] as unknown as ProtocolRead[];

export const dose = {
  id: 1,
  start_time: 0.0,
  amount: 100.0,
  duration: 0.001,
  repeats: 1,
  repeat_interval: 24.0,
  read_only: false,
  datetime: null,
  protocol: 1
} as unknown as DoseRead;

export const protocolHandlers = [
  http.get("/api/protocol", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const projectId = url.searchParams.get("project_id");
    if (projectId) {
      const filtered = protocols.filter(p => p.project === parseInt(projectId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(protocols, { status: 200 });
  }),
  http.get("/api/dose/:id", async ({ params }) => {
    await delay();
    //@ts-expect-error params.id is a string
    const doseId = parseInt(params.id, 10);
    if (doseId === dose.id) {
      return HttpResponse.json(dose, { status: 200 });
    }
    return HttpResponse.json({ error: "Dose not found" }, { status: 404 });
  }),
];
