// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { SubjectRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const subjects = [
  {
    id: 67,
    id_in_dataset: 1,
    shape: 0,
    display: true,
    metadata: "{}",
    dataset: 12,
    protocol: null,
    group: 23
  },
  {
    id: 68,
    id_in_dataset: 2,
    shape: 9,
    display: true,
    metadata: "{}",
    dataset: 12,
    protocol: null,
    group: 23
  },
  {
    id: 69,
    id_in_dataset: 3,
    shape: 18,
    display: true,
    metadata: "{}",
    dataset: 12,
    protocol: null,
    group: 23
  },
  {
    id: 70,
    id_in_dataset: 4,
    shape: 27,
    display: true,
    metadata: "{}",
    dataset: 12,
    protocol: null,
    group: 24
  },
  {
    id: 71,
    id_in_dataset: 5,
    shape: 37,
    display: true,
    metadata: "{}",
    dataset: 12,
    protocol: null,
    group: 24
  },
  {
    id: 72,
    id_in_dataset: 6,
    shape: 47,
    display: true,
    metadata: "{}",
    dataset: 12,
    protocol: null,
    group: 24
  }
] as unknown as SubjectRead[];

export const subjectHandlers = [
  http.get("/api/subject/", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const datasetId = url.searchParams.get("dataset_id");
    if (datasetId) {
      const filtered = subjects.filter(s => s.dataset === parseInt(datasetId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(subjects, { status: 200 });
  }),
];
