// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { SubjectGroupRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const subjectGroups = [
  {
    id: 31,
    subjects: [
      91,
      92,
      93
    ],
    protocols: [
      {
        id: 65,
        doses: [
          {
            id: 75,
            start_time: 0.0,
            amount: 10.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 65
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: true,
        dataset: 16,
        project: 34,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 445,
        group: 31
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 16,
    project: 34
  },
  {
    id: 32,
    subjects: [
      94,
      95,
      96
    ],
    protocols: [
      {
        id: 66,
        doses: [
          {
            id: 76,
            start_time: 0.0,
            amount: 10.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 66
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: true,
        dataset: 16,
        project: 34,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 445,
        group: 32
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 16,
    project: 34
  }
] as unknown as SubjectGroupRead[];

export const subjectGroupHandlers = [
  http.get("/api/subject_group/", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const projectId = url.searchParams.get("project_id");
    if (projectId) {
      const filtered = subjectGroups.filter(sg => sg.project === parseInt(projectId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(subjectGroups, { status: 200 });
  }),
];
