// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { SubjectGroupRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const subjectGroups = [
  {
    id: 29,
    subjects: [
      85,
      86,
      87
    ],
    protocols: [
      {
        id: 62,
        doses: [
          {
            id: 72,
            start_time: 0.0,
            amount: 10.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 62
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: true,
        dataset: 15,
        project: 33,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 429,
        group: 29
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 15,
    project: 33
  },
  {
    id: 30,
    subjects: [
      88,
      89,
      90
    ],
    protocols: [
      {
        id: 63,
        doses: [
          {
            id: 73,
            start_time: 0.0,
            amount: 10.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 63
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: true,
        dataset: 15,
        project: 33,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 429,
        group: 30
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 15,
    project: 33
  }
] as unknown as SubjectGroupRead[];

export const subjectGroupHandlers = [
  http.get("/api/subject_group/", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const projectId = url.searchParams.get("project_id");
    if (projectId) {
      const filtered = subjectGroups.filter(sg => sg.project === parseInt(projectId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(subjectGroups, { status: 200 });
  }),
];
