// Auto-generated Storybook mock - DO NOT EDIT MANUALLY
// Generated by: python manage.py generate_storybook_mocks
import { SubjectGroupRead } from "../../app/backendApi";
import { http, HttpResponse, delay } from "msw";

export const subjectGroups = [
  {
    id: 1,
    subjects: [
      1,
      2,
      3
    ],
    protocols: [
      {
        id: 2,
        doses: [
          {
            id: 2,
            start_time: 0.0,
            amount: 10.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 2
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 1",
        dose_type: "D",
        amount_per_body_weight: true,
        dataset: 1,
        project: 1,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 9,
        group: 1
      }
    ],
    name: "Data-Group 1",
    id_in_dataset: "1",
    dataset: 1,
    project: 1
  },
  {
    id: 2,
    subjects: [
      4,
      5,
      6
    ],
    protocols: [
      {
        id: 3,
        doses: [
          {
            id: 3,
            start_time: 0.0,
            amount: 10.0,
            duration: 0.0833,
            repeats: 1,
            repeat_interval: 1.0,
            read_only: false,
            datetime: null,
            protocol: 3
          }
        ],
        subjects: [],
        read_only: false,
        datetime: null,
        name: "WithData Test Dataset-Data-Group 2",
        dose_type: "D",
        amount_per_body_weight: true,
        dataset: 1,
        project: 1,
        compound: null,
        time_unit: 20,
        amount_unit: 22,
        variable: 9,
        group: 2
      }
    ],
    name: "Data-Group 2",
    id_in_dataset: "2",
    dataset: 1,
    project: 1
  }
] as unknown as SubjectGroupRead[];

export const subjectGroupHandlers = [
  http.get("/api/subject_group/", async ({ request }) => {
    await delay();
    const url = new URL(request.url);
    const projectId = url.searchParams.get("project_id");
    if (projectId) {
      const filtered = subjectGroups.filter(sg => sg.project === parseInt(projectId, 10));
      return HttpResponse.json(filtered, { status: 200 });
    }
    return HttpResponse.json(subjectGroups, { status: 200 });
  }),
];
