# Generated by Django 3.0.7 on 2020-12-02 18:09

from django.db import migrations


def load_biomarker_types(apps, schema_editor):
    init_biomarkers = [
        {
            'id': 0,
            'name': 'concentration',
            'unit': 'mg',
        }
    ]

    BiomarkerType = apps.get_model("pkpdapp", "BiomarkerType")
    for biomarker_obj in init_biomarkers:
        biomarker = BiomarkerType(
            id=0,
            name='concentration',
            description='concentration',
            unit='mg'
        )
        biomarker.save()


def delete_biomarker_types(apps, schema_editor):
    BiomarkerTypes = apps.get_model("pkpdapp", "BiomarkerTypes")
    BiomarkerTypes.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_biomarker_types, delete_biomarker_types),
    ]
