# Generated by Django 3.0.7 on 2021-03-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0004_merge_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='datetime',
            field=models.DateTimeField(blank=True, help_text='date/time the experiment was conducted. All time measurements are relative to this date/time, which is in YYYY-MM-DD HH:MM:SS format. For example, 2020-07-18 14:30:59', null=True),
        ),
    ]
