#
# This file is part of PKPDApp (https://github.com/pkpdapp-team/pkpdapp) which
# is released under the BSD 3-clause license. See accompanying LICENSE.md for
# copyright notice and full license details.
#

# Generated by Django 3.0.7 on 2021-02-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0004_merge_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='administration_type',
            field=models.CharField(choices=[('T1', 'type1'), ('T2', 'type2')],
                                   help_text='method of drug administration',
                                   max_length=10),
        ),
    ]
