# Generated by Django 3.2.23 on 2024-02-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0005_alter_derivedvariable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarkertype',
            name='mapped_qname',
            field=models.CharField(default='', help_text='qname of the mapped model variable', max_length=50),
        ),
    ]
