# Generated by Django 3.0.7 on 2021-03-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0005_auto_20210318_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomarkertype',
            name='description',
            field=models.TextField(blank=True, help_text='short description of the biomarker type', null=True),
        ),
    ]
