#
# This file is part of PKPDApp (https://github.com/pkpdapp-team/pkpdapp) which
# is released under the BSD 3-clause license. See accompanying LICENSE.md for
# copyright notice and full license details.
#
# Generated by Django 3.2.24 on 2024-03-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0007_protocol_mapped_qname'),
        ('pkpdapp', '0008_subject_group'),
    ]

    operations = [
    ]
