#
# This file is part of PKPDApp (https://github.com/pkpdapp-team/pkpdapp) which
# is released under the BSD 3-clause license. See accompanying LICENSE.md for
# copyright notice and full license details.
#
# Generated by Django 3.2.25 on 2024-04-02 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0009_merge_0007_protocol_mapped_qname_0008_subject_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='group',
            field=models.ForeignKey(
                blank=True,
                help_text='Group that uses this protocol',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='protocols',
                to='pkpdapp.subjectgroup'
            ),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='mapped_qname',
            field=models.CharField(
                blank=True,
                default='',
                help_text='qname of the mapped dosing compartment for each dose',
                max_length=50,
                null=True
            ),
        ),
    ]
