#
# This file is part of PKPDApp (https://github.com/pkpdapp-team/pkpdapp) which
# is released under the BSD 3-clause license. See accompanying LICENSE.md for
# copyright notice and full license details.
#
# Generated by Django 3.2.25 on 2024-04-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0012_subjectgroup_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(
                blank=True,
                help_text='subject group containing this subject.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subjects',
                to='pkpdapp.subjectgroup'
            ),
        ),
    ]
