#
# This file is part of PKPDApp (https://github.com/pkpdapp-team/pkpdapp) which
# is released under the BSD 3-clause license. See accompanying LICENSE.md for
# copyright notice and full license details.
#
# Generated by Django 3.2.25 on 2024-04-30 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0014_subjectgroup_id_in_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgroup',
            name='project',
            field=models.ForeignKey(
                blank=True,
                help_text='Project that this group belongs to.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='groups',
                to='pkpdapp.project'
            ),
        ),
    ]
