#
# This file is part of PKPDApp (https://github.com/pkpdapp-team/pkpdapp) which
# is released under the BSD 3-clause license. See accompanying LICENSE.md for
# copyright notice and full license details.
#
# Generated by Django 3.2.25 on 2024-11-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0017_auto_20241125_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='threshold_unit',
            field=models.ForeignKey(
                blank=True,
                help_text='unit for the threshold values',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='thresholds',
                to='pkpdapp.unit'
            ),
        ),
    ]
