# Generated by Django 3.2.25 on 2024-10-25 16:26

from django.db import migrations, models
import django.db.models.deletion
import pkpdapp.models.combined_model


def set_default_unit(apps, schema_editor):
    default_unit = pkpdapp.models.project.get_species_weight_unit()
    Project = apps.get_model("pkpdapp", "Project")
    Project.objects.update(species_weight_unit=default_unit)


def revert_set_default_unit(apps, schema_editor):
    Project = apps.get_model("pkpdapp", "Project")
    Project.objects.update(species_weight_unit=None)


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0021_resultstable_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="combinedmodel",
            name="has_extravascular",
            field=models.BooleanField(
                default=False, help_text="whether the pk model has extravascular model"
            ),
        ),
        migrations.AddField(
            model_name="combinedmodel",
            name="pk_model2",
            field=models.ForeignKey(
                blank=True,
                help_text="extravascular model",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pkpd_models2",
                to="pkpdapp.pharmacokineticmodel",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="species_weight",
            field=models.FloatField(default=1.0, help_text="species weight"),
        ),
        migrations.AddField(
            model_name="project",
            name="species_weight_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="species_weight_units",
                to="pkpdapp.unit",
            ),
        ),
        migrations.RunPython(set_default_unit, reverse_code=revert_set_default_unit),
        migrations.AlterField(
            model_name="project",
            name="species_weight_unit",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="species_weight_units",
                to="pkpdapp.unit",
            ),
        ),
        migrations.AlterField(
            model_name="derivedvariable",
            name="type",
            field=models.CharField(
                choices=[
                    ("AUC", "area under curve"),
                    ("RO", "receptor occupancy"),
                    ("FUP", "faction unbound plasma"),
                    ("BPR", "blood plasma ratio"),
                    ("TLG", "dosing lag time"),
                ],
                help_text="type of derived variable",
                max_length=3,
            ),
        ),
    ]
