#
# This file is part of PKPDApp (https://github.com/pkpdapp-team/pkpdapp) which
# is released under the BSD 3-clause license. See accompanying LICENSE.md for
# copyright notice and full license details.
#
# Generated by Django 3.2.25 on 2025-03-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0021_resultstable_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationplot',
            name='x_label',
            field=models.CharField(
                blank=True,
                help_text='label for x axis',
                max_length=100
            ),
        ),
        migrations.AddField(
            model_name='simulationplot',
            name='y2_label',
            field=models.CharField(
                blank=True,
                help_text='label for rhs y axis',
                max_length=100
            ),
        ),
        migrations.AddField(
            model_name='simulationplot',
            name='y_label',
            field=models.CharField(
                blank=True,
                help_text='label for y axis',
                max_length=100
            ),
        ),
    ]
