# Generated by Django 3.2.25 on 2024-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0023_add_anti_drug_antibodies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="name of the tag", max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="pharmacodynamicmodel",
            name="library_version",
            field=models.IntegerField(
                default=1, help_text="version number of the library model (1 or 3)"
            ),
        ),
        migrations.AddField(
            model_name="pharmacokineticmodel",
            name="library_version",
            field=models.IntegerField(
                default=1, help_text="version number of the library model (1 or 3)"
            ),
        ),
        migrations.AddField(
            model_name="pharmacodynamicmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, help_text="tags for the model", to="pkpdapp.Tag"
            ),
        ),
        migrations.AddField(
            model_name="pharmacokineticmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, help_text="tags for the model", to="pkpdapp.Tag"
            ),
        ),
    ]
