# Generated by Django 3.2.25 on 2024-12-05 12:00

from django.db import migrations


def load_tags(apps, schema_editor):
    Tag = apps.get_model("pkpdapp", "Tag")
    tags = [
        {
            "name": "1-compartment",
        },
        {
            "name": "2-compartment",
        },
        {
            "name": "3-compartment",
        },
        {
            "name": "PK",
        },
        {
            "name": "TMDD",
        },
        {
            "name": "QSS",
        },
        {
            "name": "MM",
        },
        {
            "name": "bispecific",
        },
        {
            "name": "soluble",
        },
        {
            "name": "constant",
        },
        {
            "name": "direct",
        },
        {
            "name": "indirect",
        },
        {
            "name": "TGI",
        },
        {
            "name": "DDI",
        },
    ]

    for t in tags:
        try:
            Tag.objects.get(name=t["name"])
        except Tag.DoesNotExist:
            Tag.objects.create(
                name=t["name"],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0024_add_version_and_tags"),
    ]

    operations = [
        migrations.RunPython(load_tags),
    ]
