# Generated by Django 3.2.25 on 2024-12-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0027_version_3_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
