# Generated by Django 3.2.25 on 2024-12-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0028_project_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.IntegerField(default=3),
        ),
    ]
