# Generated by Django 3.2.25 on 2024-12-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0029_alter_project_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="combinedmodel",
            name="number_of_effect_compartments",
            field=models.IntegerField(
                default=0, help_text="number of effect compartments"
            ),
        ),
        migrations.AlterField(
            model_name="pharmacodynamicmodel",
            name="model_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PK", "PK-Model"),
                    ("PKEF", "PK-Effect-Compartment"),
                    ("PKEX", "PK-Extravascular"),
                    ("PD", "PD-Model"),
                    ("TG", "Tumor-Growth"),
                    ("TGI", "Tumor-Growth-Inhibition"),
                ],
                help_text="type of model",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pharmacokineticmodel",
            name="model_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PK", "PK-Model"),
                    ("PKEF", "PK-Effect-Compartment"),
                    ("PKEX", "PK-Extravascular"),
                    ("PD", "PD-Model"),
                    ("TG", "Tumor-Growth"),
                    ("TGI", "Tumor-Growth-Inhibition"),
                ],
                help_text="type of model",
                max_length=4,
                null=True,
            ),
        ),
    ]
