# Generated by Django 3.2.25 on 2025-02-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0030_num_effect_compartments'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedvariable',
            name='secondary_variable',
            field=models.ForeignKey(blank=True, help_text='secondary variable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_derived_variables', to='pkpdapp.variable'),
        ),
        migrations.AlterField(
            model_name='derivedvariable',
            name='pk_variable',
            field=models.ForeignKey(help_text='base variable', on_delete=django.db.models.deletion.CASCADE, related_name='derived_variables', to='pkpdapp.variable'),
        ),
        migrations.AlterField(
            model_name='derivedvariable',
            name='type',
            field=models.CharField(choices=[('AUC', 'area under curve'), ('RO', 'receptor occupancy'), ('FUP', 'faction unbound plasma'), ('BPR', 'blood plasma ratio'), ('TLG', 'dosing lag time'), ('MM', 'Michaelis-Menten'), ('EMM', 'Extended Michaelis-Menten'), ('EMX', 'Emax'), ('IMX', 'Imax'), ('POW', 'Power'), ('TDI', 'Exponential Decay'), ('IND', 'Exponential Increase')], help_text='type of derived variable', max_length=3),
        ),
    ]
