# Generated by Django 3.2.25 on 2025-05-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0031_new_derived_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.TextField(
                default="", help_text="comma separated list of tags for this project"
            ),
        ),
    ]
