# Generated by Django 3.2.25 on 2025-05-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0032_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.TextField(
                blank=True,
                default='',
                help_text='comma separated list of tags for this project'
            ),
        ),
    ]
