# Generated by Django 3.2.25 on 2025-09-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0034_version_3_pd_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='amount_per_body_weight',
            field=models.BooleanField(default=False, help_text='whether the amount is per body weight'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='protocol',
            field=models.ForeignKey(blank=True, default=None, help_text='protocol containing this dose', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='pkpdapp.protocol'),
        ),
    ]
