# Generated by Django 3.2.25 on 2025-09-25 14:33

from django.db import migrations, models
import django.db.models.deletion
import pkpdapp.models.compound


def get_mol_mass_unit():
    return pkpdapp.models.compound.get_mol_mass_unit().pk


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0036_variable_unit_per_body_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="compound",
            name="target2_molecular_mass",
            field=models.FloatField(
                default=25000.0,
                help_text="molecular mass for target 2 for conversion from mol to grams",  # noqa: E501
            ),
        ),
        migrations.AddField(
            model_name="compound",
            name="target2_molecular_mass_unit",
            field=models.ForeignKey(
                default=get_mol_mass_unit,
                help_text="unit for target 2 molecular mass (e.g. g/mol)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compounds_target2_mol_mass",
                to="pkpdapp.unit",
            ),
        ),
    ]
