# Generated by Django 3.2.25 on 2025-11-13 12:08

from django.db import migrations
import importlib

v3models = importlib.import_module("pkpdapp.migrations.0027_version_3_models")
print(v3models)


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0037_second_target_mol_mass"),
    ]

    operations = [
        migrations.RunPython(v3models.load_pkpd_models),
    ]
