# Generated by Django 3.2.25 on 2025-11-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0038_add_Indirect-effect_degrader-model"),
    ]

    operations = []
