# Generated by Django 3.2.25 on 2025-12-01 17:35

from django.db import migrations, models
import django.db.models.deletion
import pkpdapp.models.compound


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0041_update_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protocol",
            name="mapped_qname",
        ),
        migrations.RemoveField(
            model_name="variable",
            name="protocol",
        ),
        migrations.AddField(
            model_name="protocol",
            name="variable",
            field=models.ForeignKey(
                blank=True,
                help_text="dosing variable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocols",
                to="pkpdapp.variable",
            ),
        ),
        migrations.AlterField(
            model_name="compound",
            name="target2_molecular_mass_unit",
            field=models.ForeignKey(
                default=pkpdapp.models.compound.get_mol_mass_unit,
                help_text="unit for target 2 molecular mass (e.g. g/mol)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compounds_target2_mol_mass",
                to="pkpdapp.unit",
            ),
        ),
        migrations.AlterField(
            model_name="derivedvariable",
            name="type",
            field=models.CharField(
                choices=[
                    ("AUC", "area under curve"),
                    ("RO", "receptor occupancy"),
                    ("FUP", "fraction unbound plasma"),
                    ("BPR", "blood plasma ratio"),
                    ("TLG", "dosing lag time"),
                    ("MM", "Michaelis-Menten"),
                    ("EMM", "Extended Michaelis-Menten"),
                    ("EMX", "Emax"),
                    ("IMX", "Imax"),
                    ("POW", "Power"),
                    ("NPW", "Negative Power"),
                    ("TDI", "Exponential Decay"),
                    ("IND", "Exponential Increase"),
                ],
                help_text="type of derived variable",
                max_length=3,
            ),
        ),
    ]
