# Generated by Django 3.2.25 on 2025-12-02 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0042_swap_variable_protocol_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Group that uses this protocol",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocols",
                to="pkpdapp.subjectgroup",
            ),
        ),
    ]
