# Generated by Django 3.2.25 on 2025-12-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0044_add_variable_to_biomarker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pd_tags',
            field=models.ManyToManyField(
                blank=True,
                help_text='saved PD model tags for this project',
                related_name='pd_projects',
                to='pkpdapp.Tag'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='pk_tags',
            field=models.ManyToManyField(
                blank=True,
                help_text='saved PK model tags for this project',
                related_name='pk_projects',
                to='pkpdapp.Tag'
            ),
        ),
    ]
