# Generated by Django 3.2.25 on 2026-01-15 18:02

from django.db import migrations, models
import django.db.models.deletion
import pkpdapp.models.combined_model


def get_default_effect_model_id():
    return pkpdapp.models.combined_model.get_default_effect_model().id


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0046_update_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="combinedmodel",
            name="pk_effect_model",
            field=models.ForeignKey(
                default=get_default_effect_model_id,
                help_text="effect compartment model",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pkpd_effect_models",
                to="pkpdapp.pharmacokineticmodel",
            ),
        ),
    ]
