# Generated by Django 3.2.25 on 2026-01-21 22:51

from django.db import migrations, models
import django.db.models.deletion
import pkpdapp.models.combined_model


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0047_combinedmodel_pk_effect_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedmodel',
            name='pk_effect_model',
            field=models.ForeignKey(default=pkpdapp.models.combined_model.get_default_effect_model, help_text='effect compartment model', on_delete=django.db.models.deletion.PROTECT, related_name='pkpd_effect_models', to='pkpdapp.pharmacokineticmodel'),
        ),
    ]
