# Generated by Django 3.2.25 on 2026-02-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0048_alter_combinedmodel_pk_effect_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='threshold_unit',
            new_name='secondary_unit',
        ),
    ]
