# Generated by Django 3.2.25 on 2026-02-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0049_rename_threshold_unit_variable_secondary_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='secondary_unit',
            field=models.ForeignKey(
                blank=True,
                help_text='display unit for secondary parameters',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='secondary_parameters',
                to='pkpdapp.unit',
            ),
        ),
    ]
