# Generated by Django 3.2.25 on 2026-02-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0051_new_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomarkertype',
            name='variable',
            field=models.ForeignKey(
                blank=True,
                help_text='mapped variable',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='biomarker_types',
                to='pkpdapp.variable',
            ),
        ),
    ]
