# Generated by Django 3.2.25 on 2026-02-10 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0052_auto_20260207_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='variable',
            field=models.ForeignKey(
                blank=True,
                help_text='dosing variable',
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='protocols',
                to='pkpdapp.variable'),
        ),
    ]
