# Generated by Django 3.2.25 on 2026-06-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0061_add_auc_units"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="loglikelihood",
            name="loglikelihood: fixed log_likelihood must have a value or biomarker_type",
        ),
        migrations.RemoveConstraint(
            model_name="loglikelihood",
            name="loglikelihood: model log_likelihood must have a variable",
        ),
        migrations.RemoveConstraint(
            model_name="loglikelihood",
            name="loglikelihood: deterministic log_likelihoods cannot have data",
        ),
        migrations.RemoveField(
            model_name="inference",
            name="algorithm",
        ),
        migrations.RemoveField(
            model_name="inference",
            name="initialization_inference",
        ),
        migrations.RemoveField(
            model_name="inference",
            name="project",
        ),
        migrations.RemoveField(
            model_name="inferencechain",
            name="inference",
        ),
        migrations.RemoveField(
            model_name="inferencefunctionresult",
            name="chain",
        ),
        migrations.RemoveField(
            model_name="inferenceoutputresult",
            name="chain",
        ),
        migrations.RemoveField(
            model_name="inferenceoutputresult",
            name="log_likelihood",
        ),
        migrations.RemoveField(
            model_name="inferenceoutputresult",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="inferenceresult",
            name="chain",
        ),
        migrations.RemoveField(
            model_name="inferenceresult",
            name="log_likelihood",
        ),
        migrations.RemoveField(
            model_name="inferenceresult",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="loglikelihood",
            name="biomarker_type",
        ),
        migrations.RemoveField(
            model_name="loglikelihood",
            name="children",
        ),
        migrations.RemoveField(
            model_name="loglikelihood",
            name="inference",
        ),
        migrations.RemoveField(
            model_name="loglikelihood",
            name="protocol_filter",
        ),
        migrations.RemoveField(
            model_name="loglikelihood",
            name="variable",
        ),
        migrations.RemoveField(
            model_name="loglikelihoodparameter",
            name="child",
        ),
        migrations.RemoveField(
            model_name="loglikelihoodparameter",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="loglikelihoodparameter",
            name="variable",
        ),
        migrations.DeleteModel(
            name="Algorithm",
        ),
        migrations.DeleteModel(
            name="Inference",
        ),
        migrations.DeleteModel(
            name="InferenceChain",
        ),
        migrations.DeleteModel(
            name="InferenceFunctionResult",
        ),
        migrations.DeleteModel(
            name="InferenceOutputResult",
        ),
        migrations.DeleteModel(
            name="InferenceResult",
        ),
        migrations.DeleteModel(
            name="LogLikelihood",
        ),
        migrations.DeleteModel(
            name="LogLikelihoodParameter",
        ),
    ]
