# Generated by Django 6.0.6

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pkpdapp", "0063_distribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="Correlation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_only",
                    models.BooleanField(
                        default=False,
                        help_text="true if object has been stored",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="datetime the object was stored.",
                        null=True,
                    ),
                ),
                (
                    "coefficient",
                    models.FloatField(
                        default=0.0,
                        help_text=(
                            "Pearson correlation coefficient of the ETAs, "
                            "in [-1, 1]"
                        ),
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "distribution_1",
                    models.ForeignKey(
                        help_text="first distribution of the correlated pair",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correlations_as_1",
                        to="pkpdapp.distribution",
                    ),
                ),
                (
                    "distribution_2",
                    models.ForeignKey(
                        help_text="second distribution of the correlated pair",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correlations_as_2",
                        to="pkpdapp.distribution",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("distribution_1", "distribution_2"),
                        name="unique_correlation_pair",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="distribution",
            name="correlations",
            field=models.ManyToManyField(
                help_text="other distributions this one is correlated with",
                through="pkpdapp.Correlation",
                to="pkpdapp.distribution",
            ),
        ),
    ]
