# Generated by Django 6.0.6 on 2026-07-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0063_add_conversation_message'),
        ('pkpdapp', '0066_update_models'),
    ]

    operations = [
    ]
