# Generated by Django 6.0.6 on 2026-07-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0068_base_subject_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='exclude',
            field=models.BooleanField(
                default=False,
                help_text='if true, this datapoint is excluded from fitting',
            ),
        ),
    ]
