# Generated by Django 6.0.6 on 2026-07-19 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0069_biomarker_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgroup',
            name='age_max',
            field=models.FloatField(blank=True, help_text='maximum age of the population (age is sampled uniformly)', null=True),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='age_min',
            field=models.FloatField(blank=True, help_text='minimum age of the population (age is sampled uniformly)', null=True),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='m2f_ratio',
            field=models.FloatField(blank=True, help_text='male-to-female ratio, i.e. probability an individual is male', null=True),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='population_region',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('EU', 'Europe'), ('ASIA', 'Asia'), ('CUSTOM', 'Custom')], help_text='region used to sample body weight', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='study_size',
            field=models.PositiveIntegerField(blank=True, help_text='number of virtual individuals (N) in this population', null=True),
        ),
        migrations.AlterField(
            model_name='derivedvariable',
            name='type',
            field=models.CharField(choices=[('AUC', 'area under curve'), ('RO', 'receptor occupancy'), ('FUP', 'fraction unbound plasma'), ('BPR', 'blood plasma ratio'), ('TLG', 'dosing lag time'), ('MM', 'Michaelis-Menten'), ('EMM', 'Extended Michaelis-Menten'), ('EMX', 'Emax'), ('IMX', 'Imax'), ('TEM', 'Time Emax'), ('TIM', 'Time Imax'), ('POW', 'Power'), ('NPW', 'Negative Power'), ('TDI', 'Exponential Decay'), ('IND', 'Exponential Increase'), ('WTC', 'Weight covariate'), ('AGC', 'Age covariate'), ('SXC', 'Sex covariate'), ('CCC', 'Custom continuous covariate'), ('CCT', 'Custom categorical covariate')], help_text='type of derived variable', max_length=3),
        ),
        migrations.CreateModel(
            name='Covariate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the covariate (e.g. albumin)', max_length=100)),
                ('type', models.CharField(choices=[('CONT', 'Continuous'), ('CAT', 'Categorical')], default='CONT', help_text='whether the covariate is continuous or categorical', max_length=4)),
                ('n_categories', models.PositiveIntegerField(blank=True, help_text='number of categories (categorical covariates only)', null=True)),
                ('category_names', models.JSONField(blank=True, help_text='optional labels for each category (categorical covariates only); index 0 is the base category', null=True)),
                ('project', models.ForeignKey(help_text='Project that this covariate belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='covariates', to='pkpdapp.project')),
                ('unit', models.ForeignKey(blank=True, help_text='unit of the covariate (continuous covariates only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covariates', to='pkpdapp.unit')),
            ],
        ),
        migrations.AddField(
            model_name='derivedvariable',
            name='covariate',
            field=models.ForeignKey(blank=True, help_text='custom covariate (CUSTOM_CONT/CUSTOM_CAT covariate types only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_variables', to='pkpdapp.covariate'),
        ),
        migrations.CreateModel(
            name='CovariatePopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('median', models.FloatField(blank=True, help_text='median value of the covariate (continuous covariates only)', null=True)),
                ('variance', models.FloatField(blank=True, help_text='variance of the log-normal random effect (continuous covariates only)', null=True)),
                ('category_probabilities', models.JSONField(blank=True, help_text='probability of each category (categorical covariates only); one entry per category, index 0 is the base category', null=True)),
                ('covariate', models.ForeignKey(help_text='custom covariate this distribution describes', on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='pkpdapp.covariate')),
                ('subject_group', models.ForeignKey(help_text='subject group (virtual population) this distribution is for', on_delete=django.db.models.deletion.CASCADE, related_name='covariate_populations', to='pkpdapp.subjectgroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject_group', 'covariate'), name='unique_group_covariate')],
            },
        ),
    ]
