# Generated by Django 6.0.6 on 2026-08-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0072_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(
                blank=True,
                default='',
                help_text="the user's department",
                max_length=100,
            ),
        ),
    ]
