# Generated by Django 6.0.8 on 2026-10-08 21:45

from django.db import migrations, models
from django.db.models import Max


def set_last_message_at(apps, schema_editor):
    Conversation = apps.get_model("pkpdapp", "Conversation")
    conversations = Conversation.objects.annotate(
        newest=Max("messages__created_at")
    ).filter(newest__isnull=False)
    for conversation in conversations:
        conversation.last_message_at = conversation.newest
        conversation.save(update_fields=["last_message_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0075_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summarized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(
            set_last_message_at,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
