# Generated by Django 6.0.8 on 2026-10-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkpdapp', '0076_conversation_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': [models.OrderBy(models.F('last_message_at'), descending=True, nulls_first=True), '-created_at']},  # noqa: E501
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='updated_at',
        ),
    ]
