#
# This file is part of PKPDApp (https://github.com/pkpdapp-team/pkpdapp) which
# is released under the BSD 3-clause license. See accompanying LICENSE.md for
# copyright notice and full license details.
#

"""
Django settings for pkpdapp project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/.

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/.
"""

import os
import sys
import dj_database_url
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType, LDAPSearchUnion

# Set BASE_DIR to two directories up
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# setup automatic pk column for models
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

DEBUG = int(os.environ.get("DEBUG", default=0))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logfile.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "level": "DEBUG",
            "formatter": "verbose",
        },
        "chatbot_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "chatbot.log"),
            "maxBytes": 1024 * 1024 * 10,  # 10 MB
            "backupCount": 3,
            "level": "DEBUG",
            "formatter": "chatbot",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "pkpdapp": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        # pydiffsol bridges the diffsol/diffsl Rust solver logs into Python via
        # pyo3-log (e.g. "BDF Solver Statistics", "Built tensor"). These are very
        # noisy at INFO; keep only warnings and errors.
        "diffsol": {
            "level": "WARNING",
            "propagate": True,
        },
        "diffsl": {
            "level": "WARNING",
            "propagate": True,
        },
        "pkpdapp.utils.chatbot": {
            "handlers": ["console", "chatbot_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "formatters": {
        "simple": {"format": "%(levelname)s %(message)s"},
        "verbose": {
            "format": "%(asctime)s %(levelname)s %(module)s %(process)d %(thread)d %(message)s"  # noqa: E501
        },
        "chatbot": {
            "format": "%(asctime)s.%(msecs)03d %(levelname)-5s %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
}

# Silence noisy INFO-level application logs (e.g. "UPDATE MODEL",
# "SimulateContext ... diffsol_odes ...") when running the test suite. Warnings
# and errors are still shown.
if "test" in sys.argv:
    LOGGING["loggers"]["pkpdapp"]["level"] = "WARNING"
    LOGGING["loggers"]["django"]["level"] = "WARNING"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get("SECRET_KEY", default="foo")


HOST_NAME = os.environ.get("HOST_NAME", "localhost")

ALLOWED_HOSTS = [
    HOST_NAME,
    "127.0.0.1",
    "testserver",
]

# Public origin of the deployed site, derived from HOST_NAME. Uses https in
# production and plain http for local development (DEBUG on). This is the single
# source of truth for the site URL used by FRONTEND_BASE_URL and
# CSRF_TRUSTED_ORIGINS below, so a deployment only needs to set HOST_NAME.
PUBLIC_ORIGIN = "{}://{}".format("http" if DEBUG else "https", HOST_NAME)


# Application definition - to use any of those you need to run `manage.py
# migrate` first

INSTALLED_APPS = [
    # standard Django apps
    "django.contrib.admin",
    "django.contrib.admindocs",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # external apps
    "dpd_static_support",
    "django_extensions",
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
    "user_visit",
    # social auth / email verification
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    # internal apps
    "pkpdapp",
]

SITE_ID = 1


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

use_predi = bool(int(os.environ.get("AUTH_PREDILOGIN_USE", "0")))
if use_predi:
    AUTH_PREDILOGIN_API_KEY = os.environ.get(
        "AUTH_PREDILOGIN_API_KEY", "your_api_key_here"
    )
    AUTH_PREDILOGIN_BASE_URL = os.environ.get(
        "AUTH_PREDILOGIN_BASE_URL", "https://api.predilogin.com"
    )
    AUTH_PREDILOGIN_USER_GROUP = os.environ.get(
        "AUTH_PREDILOGIN_USER_GROUP", "pkpdapp-users"
    )
    AUTH_PREDILOGIN_ADMIN_GROUP = os.environ.get(
        "AUTH_PREDILOGIN_ADMIN_GROUP", "pkpdapp-admins"
    )
    AUTHENTICATION_BACKENDS = [
        "pkpdapp.predilogin.PrediBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]

use_ldap = bool(int(os.environ.get("AUTH_LDAP_USE", "0")))
if use_ldap:
    AUTHENTICATION_BACKENDS = [
        "django_auth_ldap.backend.LDAPBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]
    AUTH_LDAP_SERVER_URI = os.environ.get(
        "AUTH_LDAP_SERVER_URI", "ldap://ldap.forumsys.com:389"
    )

    user_group = os.environ.get("AUTH_LDAP_USER_GROUP", None)
    admin_group = os.environ.get("AUTH_LDAP_ADMIN_GROUP", None)
    group_search = os.environ.get("AUTH_LDAP_GROUP_SEARCH", None)

    if group_search is not None:
        AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
            group_search, ldap.SCOPE_SUBTREE, "(objectClass=groupOfNames)"
        )
        AUTH_LDAP_GROUP_TYPE = GroupOfNamesType()

    if user_group is not None and group_search is not None:
        AUTH_LDAP_REQUIRE_GROUP = user_group

    if admin_group is not None and group_search is not None:
        AUTH_LDAP_USER_FLAGS_BY_GROUP = {
            "is_staff": admin_group,
            "is_superuser": admin_group,
        }

    use_direct_bind = bool(int(os.environ.get("AUTH_LDAP_DIRECT_BIND", "0")))
    if use_direct_bind:
        AUTH_LDAP_USER_DN_TEMPLATE = os.environ.get(
            "AUTH_LDAP_BIND_DN_TEMPLATE", "uid=%(user)s,dc=example,dc=com"
        )
    else:
        AUTH_LDAP_BIND_DN = os.environ.get(
            "AUTH_LDAP_BIND_DN", "cn=read-only-admin,dc=example,dc=com"
        )
        AUTH_LDAP_BIND_PASSWORD = os.environ.get("AUTH_LDAP_BIND_PASSWORD", "password")
        search_base = os.environ.get(
            "AUTH_LDAP_SEARCH_BASE", "ou=mathematicians,dc=example,dc=com"
        )
        search_filter = os.environ.get("AUTH_LDAP_SEARCH_FILTER", "(uid=%(user)s)")
        searches = [LDAPSearch(search_base, ldap.SCOPE_SUBTREE, search_filter)]
        for base_index in [2, 3, 4, 5]:
            search_base = os.environ.get(f"AUTH_LDAP_SEARCH_BASE{base_index}", None)
            if search_base is not None:
                searches.append(
                    LDAPSearch(search_base, ldap.SCOPE_SUBTREE, search_filter)
                )
        AUTH_LDAP_USER_SEARCH = LDAPSearchUnion(*searches)

# django-allauth is always available alongside whichever primary backend
# (model/predi/ldap) is configured above, so social login and email
# verification work regardless of the deployment's auth backend.
AUTHENTICATION_BACKENDS.append(
    "allauth.account.auth_backends.AuthenticationBackend"
)

# --- django-allauth configuration ---
# Frontend base URL that emailed links (e.g. the verify-email link) and OAuth
# redirects should point back to. Derived from HOST_NAME by default; set
# FRONTEND_BASE_URL explicitly only to override (e.g. a separate frontend host).
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", PUBLIC_ORIGIN)

# Require users who sign up with email/password to confirm their email before
# they are allowed to log in.
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_CONFIRM_EMAIL_ON_GET = True

# Custom adapter so the emailed confirmation link points at our API verify
# endpoint, which confirms the address and redirects to the SPA.
ACCOUNT_ADAPTER = "pkpdapp.adapters.PkpdAccountAdapter"

# Social logins provide an already-verified email, so no extra confirmation
# step is needed and we can auto-create the account.
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# When a social login's (provider-verified) email matches an existing local
# email/password account, log the user into that account
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APPS": [
            {
                "client_id": os.environ.get("GOOGLE_OAUTH_CLIENT_ID", ""),
                "secret": os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", ""),
                "key": "",
            }
        ],
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
    "github": {
        "APPS": [
            {
                "client_id": os.environ.get("GITHUB_OAUTH_CLIENT_ID", ""),
                "secret": os.environ.get("GITHUB_OAUTH_CLIENT_SECRET", ""),
                "key": "",
            }
        ],
        "SCOPE": ["read:user", "user:email"],
    },
}

# django rest framework library
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_RATES": {
        "chatbot": "30/min",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "PKPDApp API",
    "DESCRIPTION": "The API for the PKPDApp",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Chatbot / LLM (Portkey) configuration
CHATBOT_MODEL = os.environ.get("CHATBOT_MODEL", "gpt-5-nano-2025-08-07")
CHATBOT_BASE_URL = os.environ.get("CHATBOT_BASE_URL")
PORTKEY_API_KEY = os.environ.get("PORTKEY_API_KEY")


CRISPY_TEMPLATE_PACK = "bootstrap4"

MARKDOWNIFY_MARKDOWN_EXTENSIONS = [
    "mdx_math",
]

MARKDOWNIFY_WHITELIST_TAGS = [
    "a",
    "abbr",
    "acronym",
    "b",
    "blockquote",
    "em",
    "i",
    "li",
    "ol",
    "p",
    "strong",
    "ul",
    "h",
    "script",
]

MARKDOWNIFY_WHITELIST_ATTRS = [
    "href",
    "src",
    "alt",
    "type",
]

MARKDOWNIFY_WHITELIST_STYLES = [
    "color",
    "font-weight",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "user_visit.middleware.UserVisitMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    # "django_cprofile_middleware.middleware.ProfilerMiddleware",
]

# DJANGO_CPROFILE_MIDDLEWARE_REQUIRE_STAFF = False

_local_dev_origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:15173",
    "http://127.0.0.1:15173",
]

_cors_allowed_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in [
        *_cors_allowed_origins,
        f"https://{HOST_NAME}:3000",
        *_local_dev_origins,
    ]
    if origin.strip()
]

CORS_ALLOW_ALL_ORIGINS = False

CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "pkpdapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "pkpdapp", "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


X_FRAME_OPTIONS = "SAMEORIGIN"


# WSGI_APPLICATION = 'bamad.wsgi.application'

# authentication cookie settings
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 60 * 60 * 24  # 1 day
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True

# PROD ONLY
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    # TLS is terminated upstream (nginx / AWS ALB) and the request reaches
    # Django over plain HTTP. Trust the X-Forwarded-Proto header so Django
    # knows the original request was HTTPS. This is required for the OAuth
    # (allauth) callback URLs to be built as https:// and for the secure
    # session/CSRF cookies above to be set.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

WSGI_APPLICATION = "pkpdapp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        "OPTIONS": {
            # 'timeout': 20,
        },
    }
}

DATABASE_URL = os.environ.get("DATABASE_URL")
db_from_env = dj_database_url.config(
    default=DATABASE_URL, conn_max_age=500, ssl_require=False
)
DATABASES["default"].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation." "MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation." "CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation." "NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Media files (such as data sets and model files)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

STATICFILES_DIRS = []

# Staticfiles finders for locating dash app assets and related files
STATICFILES_FINDERS = [
    # Django default finders
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Forever cachable files and compression support
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = "/"


EMAIL_HOST = os.environ.get("EMAIL_HOST", default=None)
if EMAIL_HOST is None:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_PORT = int(os.environ.get("EMAIL_PORT", default="587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", default="")
# Connection encryption. Port 587 (submission) uses STARTTLS (EMAIL_USE_TLS);
# port 465 uses implicit TLS/SSL (EMAIL_USE_SSL). The two are mutually
# exclusive. Default to STARTTLS, which matches the default port 587 and most
# providers (e.g. Amazon SES SMTP). Without this, servers on port 587 reject
# auth with "530 Must issue a STARTTLS command first".
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", default="false").lower() == "true"
# Django forbids enabling both; if SSL is requested it wins (and disables TLS).
EMAIL_USE_TLS = (
    not EMAIL_USE_SSL
    and os.environ.get("EMAIL_USE_TLS", default="true").lower() == "true"
)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", default="webmaster@localhost")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
        "LOCATION": "127.0.0.1:11211",
        "OPTIONS": {"ignore_exc": True},
    }
}

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", default="webmaster@localhost")

TEST_RUNNER = "snapshottest.django.TestRunner"

_csrf_trusted_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in [
        *_csrf_trusted_origins,
        PUBLIC_ORIGIN,
        *_local_dev_origins,
    ]
    if origin.strip()
]
