name: Copyright

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: copyright
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64

      - name: install ldap 
        run: |
          sudo apt-get update
          sudo apt-get install libsasl2-dev python3-dev libldap2-dev libssl-dev

      - name: install pkpdapp
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
      - name: run copyright test
        run: |
          python run-tests.py --copyright
