name: Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: x64

      - name: install sundials
        run: |
          sudo apt-get update
          sudo apt-get install libsundials-dev libsasl2-dev python3-dev libldap2-dev libssl-dev

      - name: install pkpdapp
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install coverage codecov
      - name: run coverage
        run: |
          cd pkpdapp && coverage run manage.py test
      - name: codecov
        if: success()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cd pkpdapp && codecov
      - name: SonarCloud Scan Backend
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: pkpdapp
      - name: SonarCloud Scan Frontend
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
        with:
          projectBaseDir: frontend-v2
