name: Frontend Tests

on:
  pull_request:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      # Make sure to grab the latest version of the Playwright image
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.53.0-noble
    defaults:
      run:
        working-directory: ./frontend-v2
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/jod"
          cache: "yarn"
          cache-dependency-path: ./frontend-v2/yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test-storybook
