
name: Style tests (flake8)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: style test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: x64

      - name: install ldap 
        run: |
          sudo apt-get update
          sudo apt-get install libsasl2-dev python3-dev libldap2-dev libssl-dev

      - name: install pkpd
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install flake8
      - name: run style tests
        run: |
          python -m flake8
