name: Unit tests (OS versions)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: x64
          
      - name: install sundials (ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install libsundials-dev libsasl2-dev python3-dev libldap2-dev libssl-dev
      
      - name: install sundials (macos)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update-reset
          brew install sundials

      - name: install pkpdapp
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
      
      - name: run unit tests
        run: |
          cd pkpdapp && python manage.py test
